# Generated by Django 4.2.18 on 2025-11-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework/%Y/%m/%d/', verbose_name='作业文件')),
                ('file_type', models.CharField(max_length=10, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('ocr_processing', 'OCR识别中'), ('matching', '题目匹配中'), ('grading', '批改中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('max_score', models.FloatField(default=100.0, verbose_name='满分')),
                ('ocr_completed', models.BooleanField(default=False, verbose_name='OCR完成')),
                ('matching_completed', models.BooleanField(default=False, verbose_name='匹配完成')),
                ('grading_completed', models.BooleanField(default=False, verbose_name='批改完成')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('marked_image', models.FileField(blank=True, null=True, upload_to='homework/marked/%Y/%m/%d/', verbose_name='标记后的图片')),
                ('ocr_result', models.JSONField(blank=True, null=True, verbose_name='OCR识别结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'grading_homework_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='题号')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('fill', '填空题'), ('subjective', '主观题')], max_length=20, verbose_name='题目类型')),
                ('ocr_text', models.TextField(verbose_name='OCR识别文本')),
                ('ocr_confidence', models.FloatField(default=0.0, verbose_name='识别置信度')),
                ('question_bank_id', models.CharField(blank=True, max_length=100, verbose_name='题库题目ID')),
                ('question_stem', models.TextField(blank=True, verbose_name='题干')),
                ('correct_answer', models.TextField(blank=True, verbose_name='正确答案')),
                ('student_answer', models.TextField(blank=True, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('score', models.FloatField(default=0.0, verbose_name='得分')),
                ('max_score', models.FloatField(default=10.0, verbose_name='满分')),
                ('feedback', models.TextField(blank=True, verbose_name='批改反馈')),
                ('llm_analysis', models.JSONField(blank=True, null=True, verbose_name='LLM分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grading.homeworksubmission', verbose_name='作业提交')),
            ],
            options={
                'verbose_name': '题目批改结果',
                'verbose_name_plural': '题目批改结果',
                'db_table': 'grading_question_result',
                'ordering': ['submission', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='SimilarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_bank_id', models.CharField(max_length=100, verbose_name='题库题目ID')),
                ('question_stem', models.TextField(verbose_name='题干')),
                ('question_type', models.CharField(max_length=20, verbose_name='题目类型')),
                ('answer', models.TextField(blank=True, verbose_name='答案')),
                ('difficulty', models.CharField(blank=True, max_length=20, verbose_name='难度')),
                ('knowledge_points', models.JSONField(blank=True, default=list, verbose_name='知识点')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_questions', to='grading.questionresult', verbose_name='原题目')),
            ],
            options={
                'verbose_name': '相似题目',
                'verbose_name_plural': '相似题目',
                'db_table': 'grading_similar_question',
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_data', models.JSONField(verbose_name='试卷数据')),
                ('pdf_file', models.FileField(blank=True, upload_to='papers/pdf/%Y/%m/%d/', verbose_name='PDF文件')),
                ('jpg_files', models.JSONField(blank=True, default=list, verbose_name='JPG文件列表')),
                ('total_questions', models.IntegerField(default=0, verbose_name='题目总数')),
                ('wrong_question_count', models.IntegerField(default=0, verbose_name='错题数量')),
                ('similar_question_count', models.IntegerField(default=0, verbose_name='相似题数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='grading.homeworksubmission', verbose_name='原作业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生成试卷',
                'verbose_name_plural': '生成试卷',
                'db_table': 'grading_generated_paper',
                'ordering': ['-created_at'],
            },
        ),
    ]
