#!/bin/bash

# QAToolBox 一键部署命令
# 在阿里云服务器上执行此命令即可完成部署

echo "🚀 QAToolBox 一键部署命令"
echo "=========================="
echo ""
echo "在阿里云服务器上执行以下命令："
echo ""
echo "curl -fsSL https://raw.githubusercontent.com/shinytsing/QAToolBox/main/deploy-aliyun.sh | bash"
echo ""
echo "或者分步执行："
echo ""
echo "1. 克隆项目："
echo "git clone https://github.com/shinytsing/QAToolBox.git"
echo "cd QAToolBox"
echo ""
echo "2. 配置环境变量："
echo "cp .env.production .env"
echo "nano .env  # 编辑配置"
echo ""
echo "3. 执行部署："
echo "./deploy-aliyun.sh"
echo ""
echo "部署完成后访问："
echo "- IP: http://47.103.143.152"
echo "- 域名: http://shenyiqing.xin"
echo "- 管理员: admin / admin123"
echo ""
echo "管理命令："
echo "- 监控: ./monitor.sh"
echo "- 备份: ./backup.sh"
echo "- 日志: docker-compose logs -f web"
