# Generated by Django 4.2.18 on 2025-07-31 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='建议标题')),
                ('content', models.TextField(verbose_name='建议内容')),
                ('suggestion_type', models.CharField(choices=[('feature', '功能建议'), ('ui', '界面改进'), ('bug', 'Bug报告'), ('other', '其他')], default='feature', max_length=20, verbose_name='建议类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('reviewing', '审核中'), ('implemented', '已实现'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='用户名称')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='用户邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_response', models.TextField(blank=True, verbose_name='管理员回复')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '用户建议',
                'verbose_name_plural': '用户建议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug报告'), ('feature', '功能建议'), ('ui', '界面改进'), ('other', '其他')], default='bug', max_length=20, verbose_name='反馈类型')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='用户名称')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='用户邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_response', models.TextField(blank=True, verbose_name='管理员回复')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
