# Generated by Django 4.2.7 on 2025-08-01 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_suggestion_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='图片文件列表'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='视频文件列表'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('priority', models.CharField(choices=[('low', '普通'), ('medium', '重要'), ('high', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_popup', models.BooleanField(default=True, verbose_name='是否弹窗显示')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
