# Generated by Django 4.2.7 on 2025-08-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_suggestion_images_suggestion_videos_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('category', models.CharField(choices=[('visual', '视觉'), ('music', '音乐'), ('programming', '编程'), ('image', '图片'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ai_links/icons/', verbose_name='网站图标')),
                ('icon_url', models.URLField(blank=True, verbose_name='图标URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI友情链接',
                'verbose_name_plural': 'AI友情链接',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
