# Generated by Django 4.2.23 on 2025-08-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_ailink'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('food_randomizer', '食物随机器'), ('meditation_guide', '冥想指南'), ('guitar_training', '吉他训练'), ('life_diary', '生活日记'), ('life_goals', '人生目标'), ('checkin_calendar', '签到日历'), ('happy_days', '快乐日子'), ('douyin_analyzer', '抖音分析'), ('job_search', '求职搜索'), ('meetsomeone', '遇见某人'), ('bilibili_crawler', '哔哩哔哩爬虫'), ('vanity_tool', '虚荣工具'), ('wanderai_overview', 'WanderAI概览'), ('freemind_xmind', 'FreeMind XMind'), ('word_to_pdf', 'Word转PDF'), ('share_feature', '分享功能'), ('avatar_generator', '头像生成器'), ('food_photo_binding', '食物照片绑定'), ('content_suggestions', '内容建议'), ('user_feedback', '用户反馈'), ('admin_dashboard', '管理员仪表盘'), ('user_management', '用户管理'), ('announcement_management', '公告管理'), ('ai_links', 'AI友情链接'), ('help_center', '帮助中心'), ('version_history', '版本历史')], max_length=50, unique=True, verbose_name='功能标识')),
                ('feature_name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('description', models.TextField(blank=True, verbose_name='功能描述')),
                ('url_path', models.CharField(blank=True, max_length=200, verbose_name='URL路径')),
                ('icon', models.CharField(default='fas fa-cog', max_length=50, verbose_name='图标类名')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用'), ('maintenance', '维护中'), ('beta', '测试版')], default='enabled', max_length=20, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('public', '所有用户'), ('registered', '注册用户'), ('vip', 'VIP用户'), ('admin', '管理员'), ('hidden', '隐藏')], default='public', max_length=20, verbose_name='可见性')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '功能入口',
                'verbose_name_plural': '功能入口',
                'ordering': ['sort_order', 'feature_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ailink',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'AI友情链接', 'verbose_name_plural': 'AI友情链接'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': '系统公告', 'verbose_name_plural': '系统公告'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RemoveField(
            model_name='ailink',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='ailink',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='点击次数'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='是否审核通过'),
        ),
        migrations.AlterField(
            model_name='ailink',
            name='category',
            field=models.CharField(choices=[('ai_tools', 'AI工具'), ('coding', '编程开发'), ('design', '设计创意'), ('productivity', '效率办公'), ('learning', '学习教育'), ('entertainment', '娱乐休闲'), ('other', '其他')], default='ai_tools', max_length=20, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='ailink',
            name='description',
            field=models.TextField(blank=True, verbose_name='网站描述'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='是否弹窗显示'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('normal', '正常'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=10, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('bug', 'Bug反馈'), ('suggestion', '建议'), ('complaint', '投诉'), ('praise', '表扬'), ('question', '咨询'), ('other', '其他')], max_length=20, verbose_name='反馈类型'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='图片附件'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('reviewing', '审核中'), ('implemented', '已实现'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('feature', '功能建议'), ('improvement', '改进建议'), ('bug', 'Bug反馈'), ('other', '其他')], default='feature', max_length=20, verbose_name='建议类型'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='videos',
            field=models.JSONField(blank=True, default=list, verbose_name='视频附件'),
        ),
        migrations.CreateModel(
            name='UserFeatureAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.featureaccess', verbose_name='功能')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户功能访问',
                'verbose_name_plural': '用户功能访问',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
