# Generated by Django 4.2.7 on 2025-08-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_featureaccess_alter_ailink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='feature_key',
            field=models.CharField(choices=[('food_randomizer', '食物随机器'), ('meditation_guide', '冥想指南'), ('guitar_training', '吉他训练'), ('life_diary', '生活日记'), ('life_goals', '人生目标'), ('checkin_calendar', '签到日历'), ('happy_days', '快乐日子'), ('douyin_analyzer', '抖音分析'), ('job_search', '求职搜索'), ('meetsomeone', '遇见某人'), ('bilibili_crawler', '哔哩哔哩爬虫'), ('vanity_tool', '虚荣工具'), ('wanderai_overview', 'WanderAI概览'), ('freemind_xmind', 'FreeMind XMind'), ('word_to_pdf', 'Word转PDF'), ('share_feature', '分享功能'), ('avatar_generator', '头像生成器'), ('food_photo_binding', '食物照片绑定'), ('food_image_correction', '食物图片矫正'), ('content_suggestions', '内容建议'), ('user_feedback', '用户反馈'), ('admin_dashboard', '管理员仪表盘'), ('user_management', '用户管理'), ('announcement_management', '公告管理'), ('ai_links', 'AI友情链接'), ('help_center', '帮助中心'), ('version_history', '版本历史')], max_length=50, unique=True, verbose_name='功能标识'),
        ),
    ]
