# Generated by Django 5.2.6 on 2025-09-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_featureaccess_feature_key"),
    ]

    operations = [
        # 跳过有问题的迁移0008，直接删除模型
        migrations.DeleteModel(
            name="AILink",
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="FeatureAccess",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="Suggestion",
        ),
        migrations.DeleteModel(
            name="UserFeatureAccess",
        ),
    ]
