# Generated by Django 4.2.18 on 2025-07-21 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('TEST_CASE', 'Test Case Generator'), ('QUALITY_CHECK', 'Code Quality Check'), ('PERF_TEST', 'Performance Simulator')], max_length=20)),
                ('input_data', models.TextField()),
                ('output_file', models.FileField(upload_to='tool_outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
