# Generated by Django 4.2.18 on 2025-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolusagelog',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_previews/'),
        ),
    ]
