# Generated by Django 4.2.18 on 2025-07-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolusagelog_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolusagelog',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
