# Generated by Django 4.2.18 on 2025-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_toolusagelog_raw_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolusagelog',
            name='tool_type',
            field=models.CharField(choices=[('TEST_CASE', 'Test Case Generator'), ('QUALITY_CHECK', 'Code Quality Check'), ('PERF_TEST', 'Performance Simulator'), ('REDBOOK', 'RedBook Generator')], max_length=20),
        ),
    ]
