# Generated by Django 4.2.7 on 2025-08-02 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0004_alter_toolusagelog_tool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('xiaohongshu', '小红书'), ('douyin', '抖音'), ('netease', '网易云音乐'), ('weibo', '微博'), ('bilibili', 'B站'), ('zhihu', '知乎')], max_length=20, verbose_name='平台')),
                ('target_user_id', models.CharField(max_length=100, verbose_name='目标用户ID')),
                ('target_user_name', models.CharField(max_length=200, verbose_name='目标用户名')),
                ('subscription_types', models.JSONField(default=list, verbose_name='订阅类型')),
                ('check_frequency', models.IntegerField(choices=[(5, '5分钟'), (15, '15分钟'), (30, '30分钟'), (60, '1小时')], default=15, verbose_name='检查频率')),
                ('status', models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('error', '错误')], default='active', max_length=10, verbose_name='状态')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='最后检查时间')),
                ('last_change', models.DateTimeField(blank=True, null=True, verbose_name='最后变化时间')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社交媒体订阅',
                'verbose_name_plural': '社交媒体订阅',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform', 'target_user_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('xiaohongshu', '小红书'), ('douyin', '抖音'), ('netease', '网易云音乐'), ('weibo', '微博'), ('bilibili', 'B站'), ('zhihu', '知乎')], max_length=20, verbose_name='平台')),
                ('api_endpoint', models.URLField(verbose_name='API端点')),
                ('api_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('rate_limit', models.IntegerField(default=100, verbose_name='速率限制(次/小时)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台配置',
                'verbose_name_plural': '平台配置',
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('newPosts', '新动态'), ('newFollowers', '新关注'), ('profileChanges', '资料变化')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.socialmediasubscription', verbose_name='订阅')),
            ],
            options={
                'verbose_name': '社交媒体通知',
                'verbose_name_plural': '社交媒体通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
