# Generated by Django 4.2.7 on 2025-08-03 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0005_socialmediasubscription_socialmediaplatformconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='目标标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='目标描述')),
                ('category', models.CharField(choices=[('health', '健康'), ('career', '事业'), ('learning', '学习'), ('relationship', '人际关系'), ('finance', '财务'), ('hobby', '兴趣爱好'), ('other', '其他')], max_length=20, verbose_name='目标类别')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('paused', '暂停'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级(1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生活目标',
                'verbose_name_plural': '生活目标',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('total_diary_days', models.IntegerField(default=0, verbose_name='日记总天数')),
                ('happy_days', models.IntegerField(default=0, verbose_name='开心天数')),
                ('total_goals', models.IntegerField(default=0, verbose_name='目标总数')),
                ('completed_goals', models.IntegerField(default=0, verbose_name='已完成目标数')),
                ('mood_distribution', models.JSONField(default=dict, verbose_name='心情分布')),
                ('goal_completion_rate', models.FloatField(default=0.0, verbose_name='目标完成率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生活统计',
                'verbose_name_plural': '生活统计',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LifeGoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('progress_value', models.IntegerField(verbose_name='进度值')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='进度备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.lifegoal', verbose_name='目标')),
            ],
            options={
                'verbose_name': '目标进度',
                'verbose_name_plural': '目标进度',
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LifeDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('mood', models.CharField(choices=[('happy', '开心'), ('calm', '平静'), ('excited', '兴奋'), ('sad', '难过'), ('angry', '生气'), ('neutral', '一般')], max_length=20, verbose_name='心情')),
                ('mood_note', models.TextField(blank=True, null=True, verbose_name='心情备注')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生活日记',
                'verbose_name_plural': '生活日记',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
