# Generated by Django 4.2.18 on 2025-08-03 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0006_lifegoal_lifestatistics_lifegoalprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True, verbose_name='房间ID')),
                ('status', models.CharField(choices=[('waiting', '等待匹配'), ('active', '活跃'), ('ended', '已结束')], default='waiting', max_length=20, verbose_name='房间状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='用户1')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='用户2')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='difficulty',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难'), ('expert', '专家级')], default='medium', max_length=20, verbose_name='难度等级'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='goal_type',
            field=models.CharField(choices=[('daily', '每日目标'), ('weekly', '每周目标'), ('monthly', '每月目标'), ('quarterly', '季度目标'), ('yearly', '年度目标'), ('lifetime', '人生目标')], default='daily', max_length=20, verbose_name='目标类型'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='milestones',
            field=models.JSONField(default=list, verbose_name='里程碑'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='reminder_enabled',
            field=models.BooleanField(default=True, verbose_name='启用提醒'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='reminder_frequency',
            field=models.CharField(default='daily', max_length=20, verbose_name='提醒频率'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='reminder_time',
            field=models.TimeField(default='09:00', verbose_name='提醒时间'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='category',
            field=models.CharField(choices=[('health', '健康'), ('career', '事业'), ('learning', '学习'), ('relationship', '人际关系'), ('finance', '财务'), ('hobby', '兴趣爱好'), ('spiritual', '精神成长'), ('travel', '旅行'), ('other', '其他')], max_length=20, verbose_name='目标类别'),
        ),
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', '在线'), ('busy', '忙碌'), ('away', '离开'), ('offline', '离线')], default='offline', max_length=20, verbose_name='在线状态')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后在线时间')),
                ('is_typing', models.BooleanField(default=False, verbose_name='是否正在输入')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_users', to='tools.chatroom', verbose_name='当前房间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户在线状态',
                'verbose_name_plural': '用户在线状态',
            },
        ),
        migrations.CreateModel(
            name='HeartLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('matched', '已匹配'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='匹配时间')),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heart_link_requests', to='tools.chatroom', verbose_name='聊天室')),
                ('matched_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_heart_links', to=settings.AUTH_USER_MODEL, verbose_name='匹配用户')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_link_requests', to=settings.AUTH_USER_MODEL, verbose_name='请求者')),
            ],
            options={
                'verbose_name': '心动链接请求',
                'verbose_name_plural': '心动链接请求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('emoji', '表情')], default='text', max_length=10, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='文件URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tools.chatroom', verbose_name='聊天室')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['created_at'],
            },
        ),
    ]
