# Generated by Django 4.2.23 on 2025-08-03 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0007_chatroom_lifegoal_difficulty_lifegoal_goal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='成就标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='成就描述')),
                ('achievement_type', models.CharField(choices=[('diary', '日记成就'), ('goal', '目标成就'), ('streak', '连续成就'), ('milestone', '里程碑成就'), ('custom', '自定义成就')], max_length=20, verbose_name='成就类型')),
                ('level', models.CharField(choices=[('bronze', '铜牌'), ('silver', '银牌'), ('gold', '金牌'), ('platinum', '白金'), ('diamond', '钻石')], default='bronze', max_length=20, verbose_name='成就等级')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50, verbose_name='成就图标')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否自定义')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户成就',
                'verbose_name_plural': '用户成就',
                'ordering': ['-created_at'],
            },
        ),
    ]
