# Generated by Django 4.2.23 on 2025-08-04 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0008_userachievement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediasubscription',
            unique_together={('user', 'platform', 'target_user_id')},
        ),
    ]
