# Generated by Django 4.2.23 on 2025-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_alter_socialmediasubscription_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedianotification',
            name='notification_type',
            field=models.CharField(choices=[('newPosts', '新动态'), ('newFollowers', '新粉丝'), ('newFollowing', '被订阅人关注其他人'), ('profileChanges', '资料变化')], max_length=20, verbose_name='通知类型'),
        ),
    ]
