# Generated by Django 4.2.23 on 2025-08-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0010_update_subscription_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinVideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up主_id', models.CharField(max_length=100, verbose_name='UP主ID')),
                ('up主_name', models.CharField(max_length=200, verbose_name='UP主名称')),
                ('up主_url', models.URLField(verbose_name='UP主主页URL')),
                ('analysis_status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '分析失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('video_count', models.IntegerField(default=0, verbose_name='视频总数')),
                ('total_likes', models.BigIntegerField(default=0, verbose_name='总点赞数')),
                ('total_comments', models.BigIntegerField(default=0, verbose_name='总评论数')),
                ('total_shares', models.BigIntegerField(default=0, verbose_name='总分享数')),
                ('follower_count', models.BigIntegerField(default=0, verbose_name='粉丝数')),
                ('content_themes', models.JSONField(default=list, verbose_name='内容主题')),
                ('video_tags', models.JSONField(default=list, verbose_name='视频标签')),
                ('popular_videos', models.JSONField(default=list, verbose_name='热门视频')),
                ('posting_frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='发布频率')),
                ('screenshots', models.JSONField(default=list, verbose_name='视频截图')),
                ('product_preview', models.TextField(blank=True, null=True, verbose_name='产品功能预览')),
                ('analysis_summary', models.TextField(blank=True, null=True, verbose_name='分析总结')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '抖音视频分析',
                'verbose_name_plural': '抖音视频分析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DouyinVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, verbose_name='视频ID')),
                ('video_url', models.URLField(verbose_name='视频URL')),
                ('title', models.CharField(max_length=500, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('likes', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('shares', models.BigIntegerField(default=0, verbose_name='分享数')),
                ('views', models.BigIntegerField(default=0, verbose_name='播放量')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('theme', models.CharField(blank=True, max_length=100, null=True, verbose_name='主题')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='缩略图URL')),
                ('screenshot_urls', models.JSONField(default=list, verbose_name='截图URL列表')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tools.douyinvideoanalysis', verbose_name='分析记录')),
            ],
            options={
                'verbose_name': '抖音视频',
                'verbose_name_plural': '抖音视频',
                'ordering': ['-likes'],
            },
        ),
    ]
