# Generated by Django 4.2.23 on 2025-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_douyinvideoanalysis_douyinvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifediaryentry',
            name='music_recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='音乐推荐'),
        ),
        migrations.AddField(
            model_name='lifediaryentry',
            name='question_answers',
            field=models.JSONField(default=list, verbose_name='问题回答'),
        ),
    ]
