# Generated by Django 4.2.23 on 2025-08-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_lifediaryentry_music_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifediaryentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '生活日记', 'verbose_name_plural': '生活日记'},
        ),
        migrations.AlterUniqueTogether(
            name='lifediaryentry',
            unique_together=set(),
        ),
    ]
