# Generated by Django 4.2.23 on 2025-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_alter_lifediaryentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedianotification',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='外部链接'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='follower_avatar',
            field=models.URLField(blank=True, null=True, verbose_name='粉丝头像'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='follower_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前粉丝总数'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='follower_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='粉丝ID'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='follower_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='粉丝名称'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='following_avatar',
            field=models.URLField(blank=True, null=True, verbose_name='关注对象头像'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='following_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前关注总数'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='following_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关注对象ID'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='following_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='关注对象名称'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='new_profile_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='变化后资料'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='old_profile_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='变化前资料'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='platform_specific_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='平台特定数据'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_comments',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_content',
            field=models.TextField(blank=True, null=True, verbose_name='帖子内容'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='帖子图片'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_shares',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='分享数'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_tags',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='帖子标签'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='post_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='视频链接'),
        ),
        migrations.AddField(
            model_name='socialmedianotification',
            name='profile_changes',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='资料变化详情'),
        ),
        migrations.AlterField(
            model_name='socialmedianotification',
            name='notification_type',
            field=models.CharField(choices=[('newPosts', '新动态'), ('newFollowers', '新粉丝'), ('newFollowing', '新关注'), ('profileChanges', '资料变化')], max_length=20, verbose_name='通知类型'),
        ),
    ]
