# Generated by Django 4.2.23 on 2025-08-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_socialmedianotification_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestatistics',
            name='total_diary_count',
            field=models.IntegerField(default=0, verbose_name='日记总次数'),
        ),
    ]
