# Generated by Django 4.2.23 on 2025-08-04 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_lifestatistics_total_diary_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifediaryentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
