# Generated by Django 4.2.23 on 2025-08-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0017_workoutdashboard_fitnessworkoutsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesireItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desire_type', models.CharField(choices=[('material', '物质欲望'), ('social', '社交欲望'), ('escape', '逃避欲望'), ('achievement', '成就欲望'), ('recognition', '认可欲望')], max_length=20, verbose_name='欲望类型')),
                ('title', models.CharField(max_length=200, verbose_name='欲望标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='欲望描述')),
                ('intensity', models.IntegerField(default=3, verbose_name='欲望强度(1-5)')),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='是否已满足')),
                ('fulfillment_condition', models.TextField(blank=True, null=True, verbose_name='满足条件')),
                ('fulfillment_image_url', models.URLField(blank=True, null=True, verbose_name='兑现图片URL')),
                ('ai_generated_image', models.TextField(blank=True, null=True, verbose_name='AI生成图片描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='满足时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '欲望项目',
                'verbose_name_plural': '欲望项目',
                'ordering': ['-intensity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesireFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_completed', models.CharField(max_length=200, verbose_name='完成任务')),
                ('task_details', models.TextField(blank=True, null=True, verbose_name='任务详情')),
                ('fulfillment_image_url', models.URLField(blank=True, null=True, verbose_name='兑现图片URL')),
                ('ai_prompt', models.TextField(verbose_name='AI生成提示词')),
                ('ai_generated_image', models.TextField(blank=True, null=True, verbose_name='AI生成图片')),
                ('satisfaction_level', models.IntegerField(default=5, verbose_name='满足度(1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑现时间')),
                ('desire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.desireitem', verbose_name='欲望项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '欲望兑现记录',
                'verbose_name_plural': '欲望兑现记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesireDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_desire_level', models.IntegerField(default=50, verbose_name='当前欲望浓度')),
                ('total_desires', models.IntegerField(default=0, verbose_name='总欲望数')),
                ('fulfilled_desires', models.IntegerField(default=0, verbose_name='已满足欲望数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '欲望仪表盘',
                'verbose_name_plural': '欲望仪表盘',
            },
        ),
    ]
