# Generated by Django 4.2.23 on 2025-08-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_sponsor_vanitywealth_vanitytask_sinpoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartlinkrequest',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('matching', '匹配中'), ('matched', '已匹配'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
