# Generated by Django 4.2.23 on 2025-08-05 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0020_add_matching_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='目的地名称')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='地区')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片链接')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='热度评分')),
                ('best_season', models.CharField(blank=True, max_length=100, null=True, verbose_name='最佳季节')),
                ('average_cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='平均花费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '旅游目的地',
                'verbose_name_plural': '旅游目的地',
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('must_visit_attractions', models.JSONField(default=list, verbose_name='必去景点')),
                ('food_recommendations', models.JSONField(default=list, verbose_name='美食推荐')),
                ('transportation_guide', models.JSONField(default=dict, verbose_name='交通指南')),
                ('hidden_gems', models.JSONField(default=list, verbose_name='隐藏玩法')),
                ('weather_info', models.JSONField(default=dict, verbose_name='天气信息')),
                ('best_time_to_visit', models.TextField(blank=True, null=True, verbose_name='最佳旅行时间')),
                ('budget_estimate', models.JSONField(default=dict, verbose_name='预算估算')),
                ('travel_tips', models.JSONField(default=list, verbose_name='旅行贴士')),
                ('travel_style', models.CharField(default='general', max_length=50, verbose_name='旅行风格')),
                ('budget_range', models.CharField(default='medium', max_length=50, verbose_name='预算范围')),
                ('travel_duration', models.CharField(default='3-5天', max_length=50, verbose_name='旅行时长')),
                ('interests', models.JSONField(default=list, verbose_name='兴趣标签')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_exported', models.BooleanField(default=False, verbose_name='是否已导出')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '旅游攻略',
                'verbose_name_plural': '旅游攻略',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('travel_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.travelguide', verbose_name='旅游攻略')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '旅游攻略评价',
                'verbose_name_plural': '旅游攻略评价',
                'ordering': ['-created_at'],
                'unique_together': {('travel_guide', 'user')},
            },
        ),
    ]
