# Generated by Django 4.2.23 on 2025-08-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_jobsearchrequest_jobsearchprofile_jobapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='activity_timeline',
            field=models.JSONField(default=list, verbose_name='活动时间线'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='cost_breakdown',
            field=models.JSONField(default=dict, verbose_name='费用明细'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='daily_schedule',
            field=models.JSONField(default=list, verbose_name='每日行程'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='detailed_guide',
            field=models.JSONField(default=dict, verbose_name='详细攻略'),
        ),
    ]
