# Generated by Django 4.2.23 on 2025-08-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0023_travelguide_activity_timeline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFConversionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('pdf_to_word', 'PDF转Word'), ('word_to_pdf', 'Word转PDF'), ('pdf_to_image', 'PDF转图片'), ('image_to_pdf', '图片转PDF'), ('pdf_to_text', 'PDF转文本'), ('text_to_pdf', '文本转PDF')], max_length=20, verbose_name='转换类型')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('output_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='输出文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('conversion_time', models.FloatField(default=0.0, verbose_name='转换时间(秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('processing', '处理中')], default='processing', max_length=20, verbose_name='转换状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('download_url', models.URLField(blank=True, null=True, verbose_name='下载链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'PDF转换记录',
                'verbose_name_plural': 'PDF转换记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
