# Generated by Django 4.2.23 on 2025-08-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0024_pdfconversionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='牌名')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名')),
                ('card_type', models.CharField(choices=[('major', '大阿卡纳'), ('minor', '小阿卡纳')], max_length=10, verbose_name='牌类型')),
                ('suit', models.CharField(choices=[('wands', '权杖'), ('cups', '圣杯'), ('swords', '宝剑'), ('pentacles', '钱币'), ('major', '大阿卡纳')], max_length=20, verbose_name='花色')),
                ('number', models.IntegerField(verbose_name='数字')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='牌面图片')),
                ('upright_meaning', models.TextField(verbose_name='正位含义')),
                ('reversed_meaning', models.TextField(verbose_name='逆位含义')),
                ('keywords', models.JSONField(default=list, verbose_name='关键词')),
                ('description', models.TextField(blank=True, null=True, verbose_name='牌面描述')),
                ('symbolism', models.TextField(blank=True, null=True, verbose_name='象征意义')),
                ('advice', models.TextField(blank=True, null=True, verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '塔罗牌',
                'verbose_name_plural': '塔罗牌',
                'ordering': ['card_type', 'suit', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TarotCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('story', '故事分享'), ('question', '解牌求助'), ('experience', '经验分享'), ('discussion', '讨论')], max_length=20, verbose_name='帖子类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '塔罗社区',
                'verbose_name_plural': '塔罗社区',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarotSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='牌阵名称')),
                ('spread_type', models.CharField(choices=[('classic', '经典牌阵'), ('situation', '情景牌阵'), ('custom', '自定义牌阵')], max_length=20, verbose_name='牌阵类型')),
                ('description', models.TextField(verbose_name='牌阵描述')),
                ('card_count', models.IntegerField(verbose_name='牌数')),
                ('positions', models.JSONField(default=list, verbose_name='位置定义')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='牌阵图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '塔罗牌阵',
                'verbose_name_plural': '塔罗牌阵',
                'ordering': ['spread_type', 'card_count'],
            },
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('daily', '每日运势'), ('love', '爱情占卜'), ('career', '事业占卜'), ('health', '健康占卜'), ('spiritual', '灵性占卜'), ('custom', '自定义占卜')], max_length=20, verbose_name='占卜类型')),
                ('question', models.TextField(verbose_name='问题')),
                ('drawn_cards', models.JSONField(default=list, verbose_name='抽到的牌')),
                ('card_positions', models.JSONField(default=list, verbose_name='牌的位置')),
                ('ai_interpretation', models.TextField(blank=True, null=True, verbose_name='AI解读')),
                ('detailed_reading', models.JSONField(default=dict, verbose_name='详细解读')),
                ('user_feedback', models.TextField(blank=True, null=True, verbose_name='用户反馈')),
                ('accuracy_rating', models.IntegerField(blank=True, null=True, verbose_name='准确度评分')),
                ('mood_before', models.CharField(blank=True, max_length=50, null=True, verbose_name='占卜前心情')),
                ('mood_after', models.CharField(blank=True, max_length=50, null=True, verbose_name='占卜后心情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='占卜时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tarotspread', verbose_name='牌阵')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '塔罗占卜',
                'verbose_name_plural': '塔罗占卜',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarotEnergyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('energy_type', models.CharField(choices=[('new_moon', '新月'), ('full_moon', '满月'), ('eclipse', '日食/月食'), ('solstice', '夏至/冬至'), ('equinox', '春分/秋分'), ('daily', '日常能量')], max_length=20, verbose_name='能量类型')),
                ('energy_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='能量等级')),
                ('description', models.TextField(verbose_name='能量描述')),
                ('recommended_cards', models.JSONField(default=list, verbose_name='推荐牌')),
                ('special_reading', models.TextField(blank=True, null=True, verbose_name='特殊占卜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '塔罗能量日历',
                'verbose_name_plural': '塔罗能量日历',
                'ordering': ['-date'],
                'unique_together': {('date', 'energy_type')},
            },
        ),
        migrations.CreateModel(
            name='TarotDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='日记标题')),
                ('content', models.TextField(verbose_name='日记内容')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tarotreading', verbose_name='占卜记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '塔罗日记',
                'verbose_name_plural': '塔罗日记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarotCommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tools.tarotcommunitycomment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tools.tarotcommunity', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '塔罗社区评论',
                'verbose_name_plural': '塔罗社区评论',
                'ordering': ['created_at'],
            },
        ),
    ]
