# Generated by Django 4.2.23 on 2025-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_tarotcard_tarotcommunity_tarotspread_tarotreading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasubscription',
            name='last_follower_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='上次粉丝数'),
        ),
        migrations.AddField(
            model_name='socialmediasubscription',
            name='last_following_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='上次关注数'),
        ),
        migrations.AddField(
            model_name='socialmediasubscription',
            name='last_profile_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='上次资料数据'),
        ),
        migrations.AddField(
            model_name='socialmediasubscription',
            name='last_video_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上次最新视频ID'),
        ),
    ]
