# Generated by Django 4.2.23 on 2025-08-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_socialmediasubscription_last_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfconversionrecord',
            name='satisfaction_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='满意度评分(1-5)'),
        ),
    ]
