# Generated by Django 4.2.23 on 2025-08-07 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0027_add_satisfaction_rating_to_pdf_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='食物名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('meal_types', models.JSONField(default=list, verbose_name='适用餐种')),
                ('cuisine', models.CharField(choices=[('chinese', '中餐'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩料'), ('thai', '泰餐'), ('indian', '印度菜'), ('italian', '意大利菜'), ('french', '法餐'), ('mexican', '墨西哥菜'), ('mixed', '混合')], max_length=20, verbose_name='菜系')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='制作难度')),
                ('cooking_time', models.IntegerField(default=30, verbose_name='制作时间(分钟)')),
                ('ingredients', models.JSONField(default=list, verbose_name='主要食材')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片链接')),
                ('recipe_url', models.URLField(blank=True, null=True, verbose_name='食谱链接')),
                ('popularity_score', models.FloatField(default=0.0, verbose_name='受欢迎度')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '食物项目',
                'verbose_name_plural': '食物项目',
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodRandomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '夜宵')], max_length=20, verbose_name='餐种')),
                ('cuisine_preference', models.CharField(choices=[('chinese', '中餐'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩料'), ('thai', '泰餐'), ('indian', '印度菜'), ('italian', '意大利菜'), ('french', '法餐'), ('mexican', '墨西哥菜'), ('mixed', '混合')], default='mixed', max_length=20, verbose_name='菜系偏好')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '食物随机选择器',
                'verbose_name_plural': '食物随机选择器',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodRandomizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '夜宵')], max_length=20, verbose_name='餐种')),
                ('cuisine_preference', models.CharField(choices=[('chinese', '中餐'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩料'), ('thai', '泰餐'), ('indian', '印度菜'), ('italian', '意大利菜'), ('french', '法餐'), ('mexican', '墨西哥菜'), ('mixed', '混合')], max_length=20, verbose_name='菜系偏好')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('animation_duration', models.IntegerField(default=3000, verbose_name='动画时长(毫秒)')),
                ('total_cycles', models.IntegerField(default=0, verbose_name='总循环次数')),
                ('current_cycle', models.IntegerField(default=0, verbose_name='当前循环次数')),
                ('alternative_foods', models.JSONField(default=list, verbose_name='备选食物')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('selected_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.fooditem', verbose_name='选中的食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '食物随机选择会话',
                'verbose_name_plural': '食物随机选择会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '夜宵')], max_length=20, verbose_name='餐种')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='评分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈')),
                ('was_cooked', models.BooleanField(default=False, verbose_name='是否制作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='选择时间')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.fooditem', verbose_name='食物项目')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.foodrandomizationsession', verbose_name='随机会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '食物选择历史',
                'verbose_name_plural': '食物选择历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
