# Generated by Django 4.2.23 on 2025-08-07 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0028_fooditem_foodrandomizer_foodrandomizationsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.CharField(choices=[('fitness', '健身'), ('diary', '日记'), ('guitar', '吉他')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', '已完成'), ('skipped', '跳过'), ('rest', '休息日')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'calendar_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CheckInDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, help_text='持续时间（分钟）', null=True)),
                ('intensity', models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('workout_type', models.CharField(blank=True, choices=[('strength', '力量训练'), ('cardio', '有氧训练'), ('yoga', '瑜伽'), ('hiit', '高强度间歇'), ('flexibility', '柔韧性训练'), ('other', '其他')], max_length=50, null=True)),
                ('mood', models.CharField(blank=True, choices=[('happy', '开心'), ('sad', '难过'), ('angry', '愤怒'), ('calm', '平静'), ('excited', '兴奋'), ('tired', '疲惫'), ('other', '其他')], max_length=20, null=True)),
                ('weather', models.CharField(blank=True, max_length=20, null=True)),
                ('practice_type', models.CharField(blank=True, choices=[('chords', '和弦练习'), ('scales', '音阶练习'), ('songs', '歌曲练习'), ('theory', '乐理学习'), ('ear_training', '听力训练'), ('other', '其他')], max_length=50, null=True)),
                ('song_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='tools.checkincalendar')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.CharField(choices=[('fitness', '健身'), ('diary', '日记'), ('guitar', '吉他')], max_length=20)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'calendar_type')},
            },
        ),
        migrations.CreateModel(
            name='CheckInAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.CharField(choices=[('fitness', '健身'), ('diary', '日记'), ('guitar', '吉他')], max_length=20)),
                ('achievement_type', models.CharField(choices=[('streak_7', '连续7天'), ('streak_30', '连续30天'), ('streak_100', '连续100天'), ('total_50', '总计50次'), ('total_100', '总计100次'), ('total_365', '总计365次'), ('monthly_20', '月度20次'), ('monthly_25', '月度25次'), ('monthly_30', '月度30次')], max_length=50)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'calendar_type', 'achievement_type')},
            },
        ),
    ]
