# Generated by Django 4.2.23 on 2025-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0029_checkincalendar_checkindetail_checkinstreak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='api_used',
            field=models.CharField(default='deepseek', max_length=50, verbose_name='使用的API'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='cache_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='缓存过期时间'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='cache_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='缓存来源'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='generation_mode',
            field=models.CharField(default='standard', max_length=20, verbose_name='生成模式'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='is_cached',
            field=models.BooleanField(default=False, verbose_name='是否缓存数据'),
        ),
        migrations.CreateModel(
            name='TravelGuideCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('travel_style', models.CharField(max_length=50, verbose_name='旅行风格')),
                ('budget_range', models.CharField(max_length=50, verbose_name='预算范围')),
                ('travel_duration', models.CharField(max_length=50, verbose_name='旅行时长')),
                ('interests_hash', models.CharField(max_length=64, verbose_name='兴趣标签哈希')),
                ('guide_data', models.JSONField(verbose_name='攻略数据')),
                ('api_used', models.CharField(choices=[('deepseek', 'DeepSeek API'), ('openai', 'OpenAI API'), ('claude', 'Claude API'), ('gemini', 'Gemini API'), ('free_api_1', '免费API 1'), ('free_api_2', '免费API 2'), ('free_api_3', '免费API 3'), ('fallback', '备用数据')], max_length=50, verbose_name='使用的API')),
                ('cache_source', models.CharField(choices=[('standard_api', '标准API生成'), ('fast_api', '快速API生成'), ('cached_data', '缓存数据'), ('fallback_data', '备用数据')], max_length=50, verbose_name='缓存来源')),
                ('generation_time', models.FloatField(verbose_name='生成时间(秒)')),
                ('data_quality_score', models.FloatField(default=0.0, verbose_name='数据质量评分')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '旅游攻略缓存',
                'verbose_name_plural': '旅游攻略缓存',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['destination', 'travel_style', 'budget_range', 'travel_duration'], name='tools_trave_destina_0f3ca3_idx'), models.Index(fields=['expires_at'], name='tools_trave_expires_a18f22_idx'), models.Index(fields=['api_used'], name='tools_trave_api_use_dd95e7_idx')],
                'unique_together': {('destination', 'travel_style', 'budget_range', 'travel_duration', 'interests_hash')},
            },
        ),
    ]
