# Generated by Django 4.2.23 on 2025-08-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0030_travelguide_api_used_travelguide_cache_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cooking_steps',
            field=models.JSONField(default=list, verbose_name='制作步骤'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cooking_tools',
            field=models.JSONField(default=list, verbose_name='制作工具'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cost_level',
            field=models.CharField(choices=[('low', '经济'), ('medium', '中等'), ('high', '高档')], default='medium', max_length=20, verbose_name='成本等级'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='预估成本(元)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='highlights',
            field=models.JSONField(default=list, verbose_name='特色亮点'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='注意事项'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='概览'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='seasonings',
            field=models.JSONField(default=list, verbose_name='调味料'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tips',
            field=models.JSONField(default=list, verbose_name='制作贴士'),
        ),
    ]
