# Generated by Django 4.2.23 on 2025-08-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0031_add_travel_style_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='cooking_steps',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='cooking_tools',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='cost_level',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='seasonings',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='tips',
        ),
    ]
