# Generated by Django 4.2.23 on 2025-08-09 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0032_remove_fooditem_cooking_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPhotoBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=255, verbose_name='照片文件名')),
                ('photo_url', models.URLField(verbose_name='照片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('accuracy_score', models.FloatField(default=0.0, verbose_name='准确度评分')),
                ('binding_source', models.CharField(choices=[('manual', '手动绑定'), ('auto', '自动匹配'), ('ai', 'AI推荐')], default='manual', max_length=50, verbose_name='绑定来源')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.fooditem', verbose_name='食物项目')),
            ],
            options={
                'verbose_name': '食物照片绑定',
                'verbose_name_plural': '食物照片绑定',
                'ordering': ['-created_at'],
                'unique_together': {('food_item', 'photo_name')},
            },
        ),
        migrations.CreateModel(
            name='FoodPhotoBindingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建绑定'), ('update', '更新绑定'), ('delete', '删除绑定')], max_length=20, verbose_name='操作类型')),
                ('old_photo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='旧照片名')),
                ('new_photo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='新照片名')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tools.foodphotobinding', verbose_name='绑定关系')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '绑定历史记录',
                'verbose_name_plural': '绑定历史记录',
                'ordering': ['-performed_at'],
            },
        ),
    ]
