# Generated by Django 4.2.23 on 2025-08-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0033_foodphotobinding_foodphotobindinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='currency_info',
            field=models.JSONField(default=dict, verbose_name='汇率信息'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='destination_info',
            field=models.JSONField(default=dict, verbose_name='目的地基本信息'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='timezone_info',
            field=models.JSONField(default=dict, verbose_name='时区信息'),
        ),
    ]
