# Generated by Django 4.2.23 on 2025-08-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0035_personprofile_relationshiptag_relationshipstatistics_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='travelguidecache',
            name='tools_trave_destina_0f3ca3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='travelguidecache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='budget_amount',
            field=models.IntegerField(default=5000, verbose_name='预算金额(元)'),
        ),
        migrations.AddField(
            model_name='travelguidecache',
            name='budget_amount',
            field=models.IntegerField(default=5000, verbose_name='预算金额(元)'),
        ),
        migrations.AlterUniqueTogether(
            name='travelguidecache',
            unique_together={('destination', 'travel_style', 'budget_amount', 'budget_range', 'travel_duration', 'interests_hash')},
        ),
        migrations.AddIndex(
            model_name='travelguidecache',
            index=models.Index(fields=['destination', 'travel_style', 'budget_amount', 'budget_range', 'travel_duration'], name='tools_trave_destina_899be2_idx'),
        ),
    ]
