# Generated by Django 4.2.23 on 2025-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0036_remove_travelguidecache_tools_trave_destina_0f3ca3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='travelguidecache',
            name='tools_trave_destina_899be2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='travelguidecache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='budget_max',
            field=models.IntegerField(default=8000, verbose_name='最高预算(元)'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='budget_min',
            field=models.IntegerField(default=3000, verbose_name='最低预算(元)'),
        ),
        migrations.AddField(
            model_name='travelguidecache',
            name='budget_max',
            field=models.IntegerField(default=8000, verbose_name='最高预算(元)'),
        ),
        migrations.AddField(
            model_name='travelguidecache',
            name='budget_min',
            field=models.IntegerField(default=3000, verbose_name='最低预算(元)'),
        ),
        migrations.AlterUniqueTogether(
            name='travelguidecache',
            unique_together={('destination', 'travel_style', 'budget_min', 'budget_max', 'budget_range', 'travel_duration', 'interests_hash')},
        ),
        migrations.AddIndex(
            model_name='travelguidecache',
            index=models.Index(fields=['destination', 'travel_style', 'budget_min', 'budget_max', 'travel_duration'], name='tools_trave_destina_c796fd_idx'),
        ),
    ]
