# Generated by Django 4.2.23 on 2025-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0037_remove_travelguidecache_tools_trave_destina_899be2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinvideoanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
    ]
