# Generated by Django 4.2.23 on 2025-08-10 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0039_feature_userfirstvisit_userfeaturepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetail',
            name='feeling_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5星评分', null=True, verbose_name='感受评分'),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='is_shared_to_community',
            field=models.BooleanField(default=False, verbose_name='是否分享到社区'),
        ),
        migrations.AddField(
            model_name='checkindetail',
            name='training_parts',
            field=models.JSONField(default=list, help_text='训练的身体部位列表', verbose_name='训练部位'),
        ),
        migrations.CreateModel(
            name='FitnessTrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('description', models.TextField(verbose_name='视频描述')),
                ('video_type', models.CharField(choices=[('workout', '训练视频'), ('tutorial', '教学视频'), ('motivation', '励志视频'), ('review', '评测视频'), ('other', '其他')], max_length=20, verbose_name='视频类型')),
                ('video_file', models.FileField(upload_to='fitness_videos/', verbose_name='视频文件')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='fitness_video_thumbnails/', verbose_name='缩略图')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='分辨率')),
                ('target_parts', models.JSONField(default=list, verbose_name='目标部位')),
                ('difficulty', models.CharField(choices=[('beginner', '初学者'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], max_length=20, verbose_name='难度等级')),
                ('equipment_needed', models.JSONField(default=list, verbose_name='所需器材')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('views_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('shares_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否通过审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '健身训练视频',
                'verbose_name_plural': '健身训练视频',
                'ordering': ['-is_featured', '-views_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessTrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('description', models.TextField(verbose_name='计划描述')),
                ('plan_type', models.CharField(choices=[('strength', '力量训练'), ('cardio', '有氧训练'), ('flexibility', '柔韧性训练'), ('mixed', '综合训练'), ('custom', '自定义')], max_length=20, verbose_name='计划类型')),
                ('difficulty', models.CharField(choices=[('beginner', '初学者'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], max_length=20, verbose_name='难度等级')),
                ('duration_weeks', models.IntegerField(default=1, verbose_name='计划周数')),
                ('sessions_per_week', models.IntegerField(default=3, verbose_name='每周训练次数')),
                ('target_parts', models.JSONField(default=list, verbose_name='目标部位')),
                ('exercises', models.JSONField(default=list, verbose_name='训练动作')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '健身训练计划',
                'verbose_name_plural': '健身训练计划',
                'ordering': ['-is_featured', '-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessCommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('checkin', '打卡分享'), ('plan', '训练计划'), ('video', '训练视频'), ('achievement', '成就分享'), ('question', '健身问答'), ('motivation', '励志分享')], max_length=20, verbose_name='帖子类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('friends', '仅好友'), ('private', '仅自己')], default='public', max_length=20, verbose_name='可见性')),
                ('images', models.JSONField(default=list, verbose_name='图片')),
                ('videos', models.JSONField(default=list, verbose_name='视频')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('shares_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否通过审核')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.checkincalendar', verbose_name='关联打卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '健身社区帖子',
                'verbose_name_plural': '健身社区帖子',
                'ordering': ['-is_pinned', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessCommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('images', models.JSONField(default=list, verbose_name='图片')),
                ('likes_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否通过审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tools.fitnesscommunitycomment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tools.fitnesscommunitypost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '健身社区评论',
                'verbose_name_plural': '健身社区评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessCommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('post', '帖子点赞'), ('comment', '评论点赞')], max_length=20, verbose_name='点赞类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.fitnesscommunitycomment', verbose_name='评论')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.fitnesscommunitypost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
            options={
                'verbose_name': '健身社区点赞',
                'verbose_name_plural': '健身社区点赞',
                'unique_together': {('user', 'comment'), ('user', 'post')},
            },
        ),
    ]
