# Generated by Django 4.2.23 on 2025-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0042_timecapsule_memoryfragment_parallelmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='卡路里(千卡)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.FloatField(default=0.0, verbose_name='碳水化合物(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0.0, verbose_name='脂肪(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0.0, verbose_name='膳食纤维(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0.0, verbose_name='蛋白质(克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium',
            field=models.FloatField(default=0.0, verbose_name='钠(毫克)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0.0, verbose_name='糖分(克)'),
        ),
    ]
