# Generated by Django 4.2.23 on 2025-08-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0044_add_fitness_nutrition_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuideUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('view', '查看'), ('download', '下载'), ('use', '使用')], max_length=20, verbose_name='使用类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name': '攻略使用记录',
                'verbose_name_plural': '攻略使用记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGeneratedTravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='攻略标题')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('content', models.TextField(verbose_name='攻略内容')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='攻略摘要')),
                ('travel_style', models.CharField(default='general', max_length=50, verbose_name='旅行风格')),
                ('budget_range', models.CharField(default='medium', max_length=50, verbose_name='预算范围')),
                ('travel_duration', models.CharField(default='3-5天', max_length=50, verbose_name='旅行时长')),
                ('interests', models.JSONField(default=list, verbose_name='兴趣标签')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='travel_guides/', verbose_name='附件')),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='附件名称')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户生成旅游攻略',
                'verbose_name_plural': '用户生成旅游攻略',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='ended_at',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(db_index=True, default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tools.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heartlinkrequest',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_link_requests', to='tools.chatroom'),
        ),
        migrations.AlterField(
            model_name='heartlinkrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='heartlinkrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_link_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heartlinkrequest',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('matching', '匹配中'), ('matched', '已匹配'), ('expired', '已过期'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='unlock_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='visibility',
            field=models.CharField(choices=[('private', '仅自己'), ('public', '公开分享'), ('anonymous', '匿名分享')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='heartlinkrequest',
            unique_together={('requester', 'chat_room')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='tools_chatm_room_id_64b47f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='tools_chatm_sender__0d9510_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type', 'created_at'], name='tools_chatm_message_792309_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status', 'created_at'], name='tools_chatr_status_75a73e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user1', 'status'], name='tools_chatr_user1_i_f6013d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user2', 'status'], name='tools_chatr_user2_i_894795_idx'),
        ),
        migrations.AddIndex(
            model_name='heartlinkrequest',
            index=models.Index(fields=['requester', 'status'], name='tools_heart_request_65b31c_idx'),
        ),
        migrations.AddIndex(
            model_name='heartlinkrequest',
            index=models.Index(fields=['chat_room', 'status'], name='tools_heart_chat_ro_b9d0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='heartlinkrequest',
            index=models.Index(fields=['status', 'created_at'], name='tools_heart_status_9b9781_idx'),
        ),
        migrations.AddIndex(
            model_name='timecapsule',
            index=models.Index(fields=['user', 'created_at'], name='tools_timec_user_id_f8e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='timecapsule',
            index=models.Index(fields=['visibility', 'created_at'], name='tools_timec_visibil_d1ec8d_idx'),
        ),
        migrations.AddIndex(
            model_name='timecapsule',
            index=models.Index(fields=['unlock_time', 'unlock_condition'], name='tools_timec_unlock__89a310_idx'),
        ),
        migrations.AddIndex(
            model_name='timecapsule',
            index=models.Index(fields=['emotions'], name='timecapsule_emotions_gin'),
        ),
        migrations.AddField(
            model_name='usergeneratedtravelguide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='travelguideusage',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.usergeneratedtravelguide', verbose_name='攻略'),
        ),
        migrations.AddField(
            model_name='travelguideusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
