# Generated by Django 4.2.23 on 2025-08-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0046_buddyevent_buddyeventchat_shipbaoitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessStrengthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squat_1rm', models.FloatField(blank=True, null=True, verbose_name='深蹲1RM(kg)')),
                ('squat_1rm_date', models.DateField(blank=True, null=True, verbose_name='深蹲1RM日期')),
                ('bench_press_1rm', models.FloatField(blank=True, null=True, verbose_name='卧推1RM(kg)')),
                ('bench_press_1rm_date', models.DateField(blank=True, null=True, verbose_name='卧推1RM日期')),
                ('deadlift_1rm', models.FloatField(blank=True, null=True, verbose_name='硬拉1RM(kg)')),
                ('deadlift_1rm_date', models.DateField(blank=True, null=True, verbose_name='硬拉1RM日期')),
                ('total_1rm', models.FloatField(blank=True, null=True, verbose_name='三大项总重量(kg)')),
                ('bodyweight', models.FloatField(blank=True, null=True, verbose_name='记录时体重(kg)')),
                ('bodyweight_date', models.DateField(blank=True, null=True, verbose_name='体重记录日期')),
                ('strength_coefficient', models.FloatField(blank=True, null=True, verbose_name='力量系数(总重量/体重)')),
                ('squat_goal', models.FloatField(blank=True, null=True, verbose_name='深蹲目标(kg)')),
                ('bench_press_goal', models.FloatField(blank=True, null=True, verbose_name='卧推目标(kg)')),
                ('deadlift_goal', models.FloatField(blank=True, null=True, verbose_name='硬拉目标(kg)')),
                ('total_goal', models.FloatField(blank=True, null=True, verbose_name='总重量目标(kg)')),
                ('total_workouts', models.IntegerField(default=0, verbose_name='总训练次数')),
                ('current_streak', models.IntegerField(default=0, verbose_name='当前连续天数')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='最长连续天数')),
                ('total_duration', models.IntegerField(default=0, verbose_name='总训练时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健身力量档案',
                'verbose_name_plural': '健身力量档案',
            },
        ),
        migrations.CreateModel(
            name='ExerciseWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('squat', '深蹲'), ('bench_press', '卧推'), ('deadlift', '硬拉'), ('overhead_press', '推举'), ('barbell_row', '杠铃划船'), ('pull_up', '引体向上'), ('dip', '双杠臂屈伸'), ('lunge', '弓步蹲'), ('leg_press', '腿举'), ('leg_curl', '腿弯举'), ('leg_extension', '腿伸展'), ('calf_raise', '提踵'), ('bicep_curl', '弯举'), ('tricep_extension', '臂屈伸'), ('shoulder_press', '肩推'), ('lateral_raise', '侧平举'), ('rear_delt_fly', '后三角肌飞鸟'), ('chest_fly', '飞鸟'), ('lat_pulldown', '高位下拉'), ('face_pull', '面拉'), ('shrug', '耸肩'), ('upright_row', '直立划船'), ('good_morning', '早安式'), ('romanian_deadlift', '罗马尼亚硬拉'), ('sumo_deadlift', '相扑硬拉'), ('front_squat', '前蹲'), ('back_squat', '后蹲'), ('box_squat', '箱式深蹲'), ('pause_squat', '暂停深蹲'), ('close_grip_bench', '窄握卧推'), ('wide_grip_bench', '宽握卧推'), ('incline_bench', '上斜卧推'), ('decline_bench', '下斜卧推'), ('dumbbell_bench', '哑铃卧推'), ('dumbbell_squat', '哑铃深蹲'), ('goblet_squat', '高脚杯深蹲'), ('bulgarian_split_squat', '保加利亚分腿蹲'), ('step_up', '台阶上'), ('hip_thrust', '臀桥'), ('glute_bridge', '臀桥'), ('plank', '平板支撑'), ('side_plank', '侧平板'), ('crunch', '卷腹'), ('sit_up', '仰卧起坐'), ('russian_twist', '俄罗斯转体'), ('mountain_climber', '登山者'), ('burpee', '波比跳'), ('jumping_jack', '开合跳'), ('high_knee', '高抬腿'), ('butt_kick', '后踢腿'), ('other', '其他')], max_length=50, verbose_name='锻炼类型')),
                ('weight', models.FloatField(verbose_name='重量(kg)')),
                ('reps', models.IntegerField(verbose_name='次数')),
                ('rep_type', models.CharField(choices=[('1rm', '1RM'), ('3rm', '3RM'), ('5rm', '5RM'), ('8rm', '8RM'), ('10rm', '10RM'), ('12rm', '12RM'), ('15rm', '15RM'), ('20rm', '20RM'), ('max_reps', '最大次数'), ('custom', '自定义')], default='custom', max_length=10, verbose_name='次数类型')),
                ('sets', models.IntegerField(default=1, verbose_name='组数')),
                ('rpe', models.IntegerField(blank=True, null=True, verbose_name='RPE(1-10)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('workout_date', models.DateField(verbose_name='训练日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '锻炼重量记录',
                'verbose_name_plural': '锻炼重量记录',
                'ordering': ['-workout_date', '-created_at'],
            },
        ),
    ]
