# Generated by Django 4.2.23 on 2025-08-15 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0047_fitnessstrengthprofile_exerciseweightrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaplatformconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='lifediaryentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lifediaryentry',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='lifediaryentry',
            name='mood',
            field=models.CharField(choices=[('happy', '开心'), ('calm', '平静'), ('excited', '兴奋'), ('sad', '难过'), ('angry', '生气'), ('neutral', '一般')], db_index=True, max_length=20, verbose_name='心情'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='category',
            field=models.CharField(choices=[('health', '健康'), ('career', '事业'), ('learning', '学习'), ('relationship', '人际关系'), ('finance', '财务'), ('hobby', '兴趣爱好'), ('spiritual', '精神成长'), ('travel', '旅行'), ('other', '其他')], db_index=True, max_length=20, verbose_name='目标类别'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='goal_type',
            field=models.CharField(choices=[('daily', '每日目标'), ('weekly', '每周目标'), ('monthly', '每月目标'), ('quarterly', '季度目标'), ('yearly', '年度目标'), ('lifetime', '人生目标')], db_index=True, default='daily', max_length=20, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='priority',
            field=models.IntegerField(db_index=True, default=5, verbose_name='优先级(1-10)'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='status',
            field=models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('paused', '暂停'), ('cancelled', '已取消')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='target_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='目标日期'),
        ),
        migrations.AlterField(
            model_name='lifegoalprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lifegoalprogress',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='lifestatistics',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='socialmedianotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='socialmedianotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='socialmedianotification',
            name='notification_type',
            field=models.CharField(choices=[('newPosts', '新动态'), ('newFollowers', '新粉丝'), ('newFollowing', '新关注'), ('profileChanges', '资料变化')], db_index=True, max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='socialmediaplatformconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='socialmediaplatformconfig',
            name='platform',
            field=models.CharField(choices=[('xiaohongshu', '小红书'), ('douyin', '抖音'), ('netease', '网易云音乐'), ('weibo', '微博'), ('bilibili', 'B站'), ('zhihu', '知乎')], max_length=20, unique=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='socialmediasubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='socialmediasubscription',
            name='last_check',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='最后检查时间'),
        ),
        migrations.AlterField(
            model_name='socialmediasubscription',
            name='platform',
            field=models.CharField(choices=[('xiaohongshu', '小红书'), ('douyin', '抖音'), ('netease', '网易云音乐'), ('weibo', '微博'), ('bilibili', 'B站'), ('zhihu', '知乎')], db_index=True, max_length=20, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='socialmediasubscription',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('error', '错误')], db_index=True, default='active', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='socialmediasubscription',
            name='target_user_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='目标用户ID'),
        ),
        migrations.AlterField(
            model_name='toolusagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='toolusagelog',
            name='tool_type',
            field=models.CharField(choices=[('TEST_CASE', 'Test Case Generator'), ('QUALITY_CHECK', 'Code Quality Check'), ('PERF_TEST', 'Performance Simulator'), ('REDBOOK', 'RedBook Generator')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement_type',
            field=models.CharField(choices=[('diary', '日记成就'), ('goal', '目标成就'), ('streak', '连续成就'), ('milestone', '里程碑成就'), ('custom', '自定义成就')], db_index=True, max_length=20, verbose_name='成就类型'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='获得时间'),
        ),
        migrations.AlterField(
            model_name='useronlinestatus',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否在线'),
        ),
        migrations.AlterField(
            model_name='useronlinestatus',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='最后在线时间'),
        ),
        migrations.AlterField(
            model_name='useronlinestatus',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('busy', '忙碌'), ('away', '离开'), ('offline', '离线')], db_index=True, default='offline', max_length=20, verbose_name='在线状态'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_read'], name='tools_chatm_room_id_fce68f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user1', 'user2'], name='tools_chatr_user1_i_07d945_idx'),
        ),
        migrations.AddIndex(
            model_name='heartlinkrequest',
            index=models.Index(fields=['matched_with', 'status'], name='tools_heart_matched_a64755_idx'),
        ),
        migrations.AddIndex(
            model_name='lifediaryentry',
            index=models.Index(fields=['user', 'date'], name='tools_lifed_user_id_bcccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='lifediaryentry',
            index=models.Index(fields=['user', 'mood'], name='tools_lifed_user_id_a14229_idx'),
        ),
        migrations.AddIndex(
            model_name='lifediaryentry',
            index=models.Index(fields=['date', 'mood'], name='tools_lifed_date_0fdc13_idx'),
        ),
        migrations.AddIndex(
            model_name='lifediaryentry',
            index=models.Index(fields=['user', 'created_at'], name='tools_lifed_user_id_241b53_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoal',
            index=models.Index(fields=['user', 'status'], name='tools_lifeg_user_id_0667db_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoal',
            index=models.Index(fields=['user', 'category'], name='tools_lifeg_user_id_4ae2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoal',
            index=models.Index(fields=['status', 'target_date'], name='tools_lifeg_status_ca9a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoal',
            index=models.Index(fields=['user', 'priority'], name='tools_lifeg_user_id_3b27ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoal',
            index=models.Index(fields=['user', 'goal_type'], name='tools_lifeg_user_id_b74fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoalprogress',
            index=models.Index(fields=['goal', 'date'], name='tools_lifeg_goal_id_735172_idx'),
        ),
        migrations.AddIndex(
            model_name='lifegoalprogress',
            index=models.Index(fields=['date', 'progress_value'], name='tools_lifeg_date_2989ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lifestatistics',
            index=models.Index(fields=['user', 'date'], name='tools_lifes_user_id_0e4029_idx'),
        ),
        migrations.AddIndex(
            model_name='lifestatistics',
            index=models.Index(fields=['date', 'goal_completion_rate'], name='tools_lifes_date_ee4aca_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedianotification',
            index=models.Index(fields=['subscription', 'created_at'], name='tools_socia_subscri_3ccb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedianotification',
            index=models.Index(fields=['is_read', 'created_at'], name='tools_socia_is_read_ba0daf_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedianotification',
            index=models.Index(fields=['notification_type', 'created_at'], name='tools_socia_notific_35edf5_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaplatformconfig',
            index=models.Index(fields=['is_active'], name='tools_socia_is_acti_85d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'status'], name='tools_socia_user_id_96487a_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['platform', 'status'], name='tools_socia_platfor_2fea62_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['status', 'last_check'], name='tools_socia_status_cc3208_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'platform'], name='tools_socia_user_id_fc8bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusagelog',
            index=models.Index(fields=['user', 'tool_type'], name='tools_toolu_user_id_e8e76e_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusagelog',
            index=models.Index(fields=['created_at', 'tool_type'], name='tools_toolu_created_693d90_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusagelog',
            index=models.Index(fields=['user', 'created_at'], name='tools_toolu_user_id_bb777b_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'achievement_type'], name='tools_usera_user_id_c723be_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'level'], name='tools_usera_user_id_bb1107_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement_type', 'created_at'], name='tools_usera_achieve_afaddc_idx'),
        ),
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['status', 'last_seen'], name='tools_usero_status_4ee934_idx'),
        ),
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['is_online', 'last_seen'], name='tools_usero_is_onli_e66a11_idx'),
        ),
    ]
