# Generated by Django 4.2.23 on 2025-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0057_create_diary_related_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedianotification',
            name='data',
            field=models.JSONField(default=dict, verbose_name='详细数据'),
        ),
    ]
