# Generated by Django 4.2.23 on 2025-08-22 13:34

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0059_add_training_plan_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyinvideo',
            name='crawled_at',
            field=models.DateTimeField(default=timezone.now, verbose_name='爬取时间'),
        ),
    ]
