# Generated by Django 4.2.23 on 2025-08-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0060_auto_20250822_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedFitnessUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=25, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10, verbose_name='性别')),
                ('height', models.FloatField(default=170.0, verbose_name='身高(cm)')),
                ('weight', models.FloatField(default=70.0, verbose_name='当前体重(kg)')),
                ('body_fat_percentage', models.FloatField(blank=True, null=True, verbose_name='体脂率(%)')),
                ('bmr', models.FloatField(blank=True, null=True, verbose_name='基础代谢率')),
                ('goal', models.CharField(choices=[('lose_weight', '减脂'), ('gain_muscle', '增肌'), ('maintain', '维持体重')], default='maintain', max_length=20, verbose_name='健身目标')),
                ('intensity', models.CharField(choices=[('conservative', '保守型'), ('balanced', '均衡型'), ('aggressive', '激进型')], default='balanced', max_length=20, verbose_name='目标强度')),
                ('activity_level', models.CharField(choices=[('sedentary', '久坐'), ('light', '轻度活动'), ('moderate', '中度活动'), ('high', '重度活动')], default='moderate', max_length=20, verbose_name='日常活动量')),
                ('dietary_preferences', models.JSONField(default=list, verbose_name='饮食偏好')),
                ('allergies', models.JSONField(default=list, verbose_name='过敏食物')),
                ('training_days_per_week', models.IntegerField(default=3, verbose_name='每周训练天数')),
                ('training_intensity', models.CharField(default='moderate', max_length=20, verbose_name='训练强度')),
                ('training_duration', models.IntegerField(default=60, verbose_name='训练时长(分钟)')),
                ('selected_badges', models.JSONField(default=dict, verbose_name='选中的徽章')),
                ('badge_showcase_layout', models.CharField(default='grid', max_length=20, verbose_name='徽章展示布局')),
                ('show_achievements_publicly', models.BooleanField(default=True, verbose_name='公开显示成就')),
                ('profile_visibility', models.CharField(default='public', max_length=20, verbose_name='资料可见性')),
                ('show_stats_publicly', models.BooleanField(default=True, verbose_name='公开显示统计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健身用户档案',
                'verbose_name_plural': '健身用户档案',
            },
        ),
    ]
