# Generated by Django 4.2.23 on 2025-08-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0062_auto_20250822_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipbaoitem',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='shipbaoitem',
            name='location_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地区'),
        ),
        migrations.AddField(
            model_name='shipbaoitem',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='详细地址'),
        ),
    ]
