# Generated by Django 4.2.23 on 2025-08-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0066_auto_20250825_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuserprofile',
            name='selected_badge',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                to='tools.fitnessachievement',
                verbose_name='已佩戴徽章'
            ),
        ),
    ]
