# Generated by Django 4.2.7 on 2025-08-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0067_add_selected_badge_id'),
    ]

    operations = [
    ]
