# Generated by Django 5.2.5 on 2025-09-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0070_achievementunlocklog_bodypart_chatnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipbaoinquiry',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipbao_inquiries', to='tools.chatroom', verbose_name='聊天室'),
        ),
    ]
