# Generated by Django 4.2.7 on 2025-09-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0071_alter_shipbaoinquiry_chat_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkindetail",
            name="checkin",
        ),
        migrations.DeleteModel(
            name="DouyinVideo",
        ),
        migrations.DeleteModel(
            name="DouyinVideoAnalysis",
        ),
        migrations.RemoveField(
            model_name="socialmedianotification",
            name="subscription",
        ),
        migrations.DeleteModel(
            name="SocialMediaPlatformConfig",
        ),
        migrations.AlterUniqueTogether(
            name="socialmediasubscription",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="socialmediasubscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="CheckInDetail",
        ),
        migrations.DeleteModel(
            name="SocialMediaNotification",
        ),
        migrations.DeleteModel(
            name="SocialMediaSubscription",
        ),
    ]
