# Generated by Django 5.0.1 on 2025-09-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0073_remove_achievementunlocklog_achievement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="元数据"),
        ),
    ]
