# Generated by Django 5.0.1 on 2025-09-16 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0074_chatmessage_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrojanUserConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=255, verbose_name="Trojan密码")),
                ("server_host", models.CharField(default="shenyiqing.xin", max_length=255, verbose_name="服务器地址")),
                ("server_port", models.IntegerField(default=443, verbose_name="服务器端口")),
                ("local_port", models.IntegerField(default=1080, verbose_name="本地端口")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("last_used", models.DateTimeField(blank=True, null=True, verbose_name="最后使用时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="trojan_config", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Trojan用户配置",
                "verbose_name_plural": "Trojan用户配置",
                "db_table": "trojan_user_config",
            },
        ),
        migrations.CreateModel(
            name="TrojanUsageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bytes_sent", models.BigIntegerField(default=0, verbose_name="发送字节数")),
                ("bytes_received", models.BigIntegerField(default=0, verbose_name="接收字节数")),
                ("connection_count", models.IntegerField(default=0, verbose_name="连接次数")),
                ("session_duration", models.IntegerField(default=0, verbose_name="会话时长(秒)")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trojan_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trojan使用日志",
                "verbose_name_plural": "Trojan使用日志",
                "db_table": "trojan_usage_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="trojan_usag_user_id_2f0cc4_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="trojan_usag_ip_addr_d381c2_idx"),
                ],
            },
        ),
    ]
