# Generated by Django 5.0.1 on 2025-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0074_chatmessage_metadata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TravelGuideCache",
        ),
        migrations.RemoveField(
            model_name="travelguide",
            name="cache_expires_at",
        ),
        migrations.RemoveField(
            model_name="travelguide",
            name="cache_source",
        ),
        migrations.RemoveField(
            model_name="travelguide",
            name="is_cached",
        ),
        migrations.AlterField(
            model_name="travelguide",
            name="api_used",
            field=models.CharField(default="llm_service", max_length=50, verbose_name="使用的API"),
        ),
    ]
