# Generated by Django 5.0.1 on 2025-09-16 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0075_trojanuserconfig_trojanusagelog"),
        ("tools", "0076_remove_cache_fields"),
    ]

    operations = []
