# Generated by Django 4.2.18 on 2025-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0077_merge_20250916_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='is_cached',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否缓存数据'),
        ),
    ]
