# Generated by Django 4.2.18 on 2025-09-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0078_travelguide_is_cached'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouyinVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(default='', max_length=100, unique=True, verbose_name='视频ID')),
                ('author_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者ID')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者名称')),
                ('title', models.TextField(blank=True, null=True, verbose_name='视频标题')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面URL')),
                ('video_url', models.URLField(default='', verbose_name='视频URL')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('shares', models.IntegerField(default=0, verbose_name='分享数')),
                ('music', models.JSONField(default=dict, verbose_name='音乐信息')),
                ('hashtags', models.JSONField(default=list, verbose_name='话题标签')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='视频创建时间')),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name': '抖音视频',
                'verbose_name_plural': '抖音视频',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='DouyinVideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='', verbose_name='视频URL')),
                ('video_id', models.CharField(default='', max_length=100, unique=True, verbose_name='视频ID')),
                ('author_name', models.CharField(default='', max_length=100, verbose_name='作者名称')),
                ('title', models.TextField(default='', verbose_name='视频标题')),
                ('description', models.TextField(blank=True, verbose_name='视频描述')),
                ('music_info', models.JSONField(default=dict, verbose_name='音乐信息')),
                ('statistics', models.JSONField(default=dict, verbose_name='统计数据')),
                ('hashtags', models.JSONField(default=list, verbose_name='话题标签')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='视频创建时间')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分析时间')),
            ],
            options={
                'verbose_name': '抖音视频分析',
                'verbose_name_plural': '抖音视频分析',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, unique=True, verbose_name='平台')),
                ('name', models.CharField(max_length=50, verbose_name='平台名称')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('api_config', models.JSONField(default=dict, verbose_name='API配置')),
                ('crawler_config', models.JSONField(default=dict, verbose_name='爬虫配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台配置',
                'verbose_name_plural': '平台配置',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('xiaohongshu', '小红书'), ('douyin', '抖音'), ('netease', '网易云音乐'), ('weibo', '微博'), ('bilibili', 'B站')], db_index=True, max_length=20, verbose_name='平台')),
                ('target_user_id', models.CharField(db_index=True, max_length=100, verbose_name='目标用户ID')),
                ('target_user_name', models.CharField(max_length=200, verbose_name='目标用户名')),
                ('subscription_types', models.JSONField(default=list, verbose_name='订阅类型')),
                ('check_frequency', models.IntegerField(choices=[(5, '5分钟'), (15, '15分钟'), (30, '30分钟'), (60, '1小时')], default=15, verbose_name='检查频率')),
                ('status', models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('error', '错误')], db_index=True, default='active', max_length=10, verbose_name='状态')),
                ('last_check', models.DateTimeField(auto_now=True, db_index=True, verbose_name='最后检查时间')),
                ('last_change', models.DateTimeField(blank=True, null=True, verbose_name='最后变化时间')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('last_follower_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='上次粉丝数')),
                ('last_video_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='上次最新视频ID')),
                ('last_following_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='上次关注数')),
                ('last_profile_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='上次资料数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社交媒体订阅',
                'verbose_name_plural': '社交媒体订阅',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('newPosts', '新动态'), ('newFollowers', '新粉丝'), ('newFollowing', '新关注'), ('profileChanges', '资料变化')], db_index=True, max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('data', models.JSONField(default=dict, verbose_name='详细数据')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='外部链接')),
                ('follower_avatar', models.URLField(blank=True, null=True, verbose_name='粉丝头像')),
                ('follower_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前粉丝总数')),
                ('follower_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='粉丝ID')),
                ('follower_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='粉丝名称')),
                ('following_avatar', models.URLField(blank=True, null=True, verbose_name='关注对象头像')),
                ('following_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前关注总数')),
                ('following_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='关注对象ID')),
                ('following_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='关注对象名称')),
                ('new_profile_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='变化后资料')),
                ('old_profile_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='变化前资料')),
                ('platform_specific_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='平台特定数据')),
                ('post_comments', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('post_content', models.TextField(blank=True, null=True, verbose_name='帖子内容')),
                ('post_images', models.JSONField(blank=True, default=list, null=True, verbose_name='帖子图片')),
                ('post_likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('post_shares', models.IntegerField(blank=True, default=0, null=True, verbose_name='分享数')),
                ('post_tags', models.JSONField(blank=True, default=list, null=True, verbose_name='帖子标签')),
                ('post_video_url', models.URLField(blank=True, null=True, verbose_name='视频链接')),
                ('profile_changes', models.JSONField(blank=True, default=dict, null=True, verbose_name='资料变化详情')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.socialmediasubscription', verbose_name='订阅')),
            ],
            options={
                'verbose_name': '社交媒体通知',
                'verbose_name_plural': '社交媒体通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'status'], name='tools_socia_user_id_96487a_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['platform', 'status'], name='tools_socia_platfor_2fea62_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['status', 'last_check'], name='tools_socia_status_cc3208_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'platform'], name='tools_socia_user_id_fc8bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'status', 'last_check'], name='tools_socia_user_id_37bb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['platform', 'status', 'last_check'], name='tools_socia_platfor_b4a13d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediasubscription',
            index=models.Index(fields=['user', 'platform', 'status'], name='tools_socia_user_id_54ff61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediasubscription',
            unique_together={('user', 'platform', 'target_user_id')},
        ),
        migrations.AddIndex(
            model_name='socialmedianotification',
            index=models.Index(fields=['subscription', 'created_at'], name='tools_socia_subscri_3ccb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedianotification',
            index=models.Index(fields=['is_read', 'created_at'], name='tools_socia_is_read_ba0daf_idx'),
        ),
    ]
