# Generated by Django 4.2.18 on 2025-09-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0079_fix_social_media_app_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasubscription',
            name='check_frequency',
        ),
    ]
