# Generated by Django 4.2.18 on 2025-09-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0080_remove_check_frequency_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('storage_state', models.JSONField(help_text='Playwright storage state', verbose_name='存储状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Cookie 会话',
                'verbose_name_plural': 'Cookie 会话',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='UserCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='如: boss, lagou, liepin 等', max_length=50, verbose_name='平台')),
                ('cookies', models.JSONField(help_text='存储完整的 cookie 信息', verbose_name='Cookie 数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户 Cookie',
                'verbose_name_plural': '用户 Cookie',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
