# Generated by Django 4.2.18 on 2026-08-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0083_requirement_rag"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="requirementchunk",
            new_name="tools_requi_documen_895a9e_idx",
            old_name="tools_requi_documen_4d601a_idx",
        ),
        migrations.RenameIndex(
            model_name="requirementdocument",
            new_name="tools_requi_owner_i_18a14d_idx",
            old_name="tools_requi_owner_i_0bfbdc_idx",
        ),
    ]
