# QAToolbox/apps/tools/management/commands/populate_nutrition_data.py
"""
填充食物营养数据的管理命令
"""

from django.core.management.base import BaseCommand

from apps.tools.models import FoodNutrition


class Command(BaseCommand):
    help = "填充食物营养数据到数据库"

    def handle(self, *args, **options):
        self.stdout.write("开始填充食物营养数据...")

        # 清除现有数据
        FoodNutrition.objects.all().delete()

        # 食物营养数据
        foods_data = [
            # 中餐
            {
                "name": "宫保鸡丁",
                "english_name": "Kung Pao Chicken",
                "cuisine": "chinese",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 25,
                "serving_size": 150,
                "calories": 350,
                "protein": 28.5,
                "fat": 18.2,
                "carbohydrates": 12.8,
                "dietary_fiber": 2.1,
                "sugar": 8.5,
                "sodium": 850,
                "potassium": 420,
                "calcium": 45,
                "iron": 2.8,
                "vitamin_c": 15,
                "ingredients": ["鸡肉", "花生", "干辣椒", "葱姜蒜", "豆瓣酱"],
                "allergens": ["坚果", "大豆"],
                "tags": ["川菜", "经典", "麻辣"],
                "is_high_protein": True,
                "health_score": random.randint(45, 85),  # 随机健康评分
                "popularity_score": 9.2,
                "image_url": "/static/img/food/default-food.svg",
                "description": "经典川菜，口感麻辣鲜香，营养丰富",
            },
            {
                "name": "麻婆豆腐",
                "english_name": "Mapo Tofu",
                "cuisine": "chinese",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 20,
                "serving_size": 200,
                "calories": 280,
                "protein": 15.6,
                "fat": 18.4,
                "carbohydrates": 8.2,
                "dietary_fiber": 3.2,
                "sugar": 3.1,
                "sodium": 780,
                "potassium": 320,
                "calcium": 180,
                "iron": 3.2,
                "vitamin_c": 8,
                "ingredients": ["豆腐", "猪肉末", "豆瓣酱", "花椒", "葱"],
                "allergens": ["大豆"],
                "tags": ["川菜", "素食友好", "麻辣"],
                "is_vegetarian": True,
                "health_score": 80,
                "popularity_score": 8.8,
                "image_url": "/static/img/food/default-food.svg",
                "description": "川菜经典，麻辣鲜香，豆腐嫩滑",
            },
            {
                "name": "糖醋里脊",
                "english_name": "Sweet and Sour Pork",
                "cuisine": "chinese",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 25,
                "serving_size": 180,
                "calories": 320,
                "protein": 22.4,
                "fat": 15.8,
                "carbohydrates": 22.6,
                "dietary_fiber": 1.2,
                "sugar": 18.5,
                "sodium": 650,
                "potassium": 380,
                "calcium": 25,
                "iron": 2.1,
                "vitamin_c": 12,
                "ingredients": ["里脊肉", "糖", "醋", "淀粉", "番茄酱"],
                "allergens": [],
                "tags": ["酸甜", "经典", "家常菜"],
                "is_high_protein": True,
                "health_score": 65,
                "popularity_score": 8.5,
                "image_url": "/static/img/food/default-food.svg",
                "description": "酸甜可口，开胃下饭",
            },
            {
                "name": "蛋炒饭",
                "english_name": "Egg Fried Rice",
                "cuisine": "chinese",
                "meal_type": "main",
                "difficulty": 1,
                "cooking_time": 15,
                "serving_size": 250,
                "calories": 300,
                "protein": 12.8,
                "fat": 8.5,
                "carbohydrates": 45.2,
                "dietary_fiber": 1.8,
                "sugar": 2.1,
                "sodium": 520,
                "potassium": 180,
                "calcium": 50,
                "iron": 2.5,
                "vitamin_c": 5,
                "ingredients": ["米饭", "鸡蛋", "葱花", "酱油", "植物油"],
                "allergens": ["鸡蛋"],
                "tags": ["简单", "快手", "家常"],
                "health_score": 70,
                "popularity_score": 9.0,
                "image_url": "/static/img/food/default-food.svg",
                "description": "简单美味，经典家常菜",
            },
            # 意大利菜
            {
                "name": "意大利面",
                "english_name": "Spaghetti",
                "cuisine": "italian",
                "meal_type": "main",
                "difficulty": 2,
                "cooking_time": 20,
                "serving_size": 200,
                "calories": 280,
                "protein": 11.2,
                "fat": 8.5,
                "carbohydrates": 42.8,
                "dietary_fiber": 3.2,
                "sugar": 6.5,
                "sodium": 480,
                "potassium": 320,
                "calcium": 35,
                "iron": 2.1,
                "vitamin_c": 18,
                "ingredients": ["意大利面", "番茄酱", "橄榄油", "罗勒", "大蒜"],
                "allergens": ["麸质"],
                "tags": ["意式", "经典", "西餐"],
                "health_score": random.randint(45, 85),  # 随机健康评分
                "popularity_score": 8.7,
                "image_url": "/static/img/food/default-food.svg",
                "description": "经典意式料理，简单美味",
            },
            {
                "name": "披萨",
                "english_name": "Pizza",
                "cuisine": "italian",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 30,
                "serving_size": 180,
                "calories": 400,
                "protein": 18.5,
                "fat": 16.8,
                "carbohydrates": 48.2,
                "dietary_fiber": 2.8,
                "sugar": 5.2,
                "sodium": 920,
                "potassium": 280,
                "calcium": 220,
                "iron": 2.8,
                "vitamin_c": 12,
                "ingredients": ["面团", "番茄酱", "奶酪", "香肠", "橄榄油"],
                "allergens": ["麸质", "乳制品"],
                "tags": ["意式", "芝士", "烘焙"],
                "health_score": 60,
                "popularity_score": 9.1,
                "image_url": "/static/img/food/default-food.svg",
                "description": "意式经典，香浓可口",
            },
            # 日料
            {
                "name": "寿司",
                "english_name": "Sushi",
                "cuisine": "japanese",
                "meal_type": "main",
                "difficulty": 4,
                "cooking_time": 30,
                "serving_size": 120,
                "calories": 200,
                "protein": 18.5,
                "fat": 2.8,
                "carbohydrates": 28.5,
                "dietary_fiber": 1.5,
                "sugar": 3.2,
                "sodium": 680,
                "potassium": 320,
                "calcium": 25,
                "iron": 1.8,
                "vitamin_c": 5,
                "ingredients": ["米饭", "三文鱼", "海苔", "芥末", "醋"],
                "allergens": ["鱼类"],
                "tags": ["日式", "生鱼", "精致"],
                "is_high_protein": True,
                "is_low_fat": True,
                "health_score": 85,
                "popularity_score": 8.9,
                "image_url": "/static/img/food/default-food.svg",
                "description": "精致日式料理，营养丰富",
            },
            {
                "name": "拉面",
                "english_name": "Ramen",
                "cuisine": "japanese",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 25,
                "serving_size": 350,
                "calories": 350,
                "protein": 15.8,
                "fat": 12.5,
                "carbohydrates": 42.8,
                "dietary_fiber": 3.2,
                "sugar": 4.5,
                "sodium": 1250,
                "potassium": 420,
                "calcium": 65,
                "iron": 2.8,
                "vitamin_c": 8,
                "ingredients": ["面条", "高汤", "叉烧", "海苔", "鸡蛋"],
                "allergens": ["麸质", "鸡蛋"],
                "tags": ["日式", "汤面", "浓郁"],
                "health_score": 65,
                "popularity_score": 8.6,
                "image_url": "/static/img/food/default-food.svg",
                "description": "日式拉面，汤浓面滑",
            },
            # 美式
            {
                "name": "汉堡",
                "english_name": "Burger",
                "cuisine": "american",
                "meal_type": "main",
                "difficulty": 2,
                "cooking_time": 15,
                "serving_size": 220,
                "calories": 450,
                "protein": 25.8,
                "fat": 22.5,
                "carbohydrates": 38.2,
                "dietary_fiber": 3.2,
                "sugar": 6.8,
                "sodium": 980,
                "potassium": 380,
                "calcium": 120,
                "iron": 3.2,
                "vitamin_c": 8,
                "ingredients": ["牛肉饼", "面包", "生菜", "番茄", "奶酪"],
                "allergens": ["麸质", "乳制品"],
                "tags": ["美式", "快餐", "汉堡"],
                "is_high_protein": True,
                "health_score": 55,
                "popularity_score": 8.8,
                "image_url": "/static/img/food/default-food.svg",
                "description": "美式快餐，方便快捷",
            },
            {
                "name": "热狗",
                "english_name": "Hot Dog",
                "cuisine": "american",
                "meal_type": "main",
                "difficulty": 1,
                "cooking_time": 10,
                "serving_size": 150,
                "calories": 300,
                "protein": 12.5,
                "fat": 18.8,
                "carbohydrates": 22.5,
                "dietary_fiber": 2.1,
                "sugar": 4.2,
                "sodium": 1050,
                "potassium": 220,
                "calcium": 85,
                "iron": 2.1,
                "vitamin_c": 6,
                "ingredients": ["香肠", "面包", "芥末", "洋葱", "番茄酱"],
                "allergens": ["麸质"],
                "tags": ["美式", "快餐", "简单"],
                "health_score": 50,
                "popularity_score": 7.8,
                "image_url": "/static/img/food/default-food.svg",
                "description": "美式经典，简单美味",
            },
            # 健康餐
            {
                "name": "沙拉",
                "english_name": "Salad",
                "cuisine": "healthy",
                "meal_type": "appetizer",
                "difficulty": 1,
                "cooking_time": 10,
                "serving_size": 200,
                "calories": 120,
                "protein": 6.5,
                "fat": 8.2,
                "carbohydrates": 8.5,
                "dietary_fiber": 4.2,
                "sugar": 6.8,
                "sodium": 220,
                "potassium": 420,
                "calcium": 85,
                "iron": 2.1,
                "vitamin_c": 45,
                "vitamin_a": 850,
                "ingredients": ["生菜", "番茄", "黄瓜", "橄榄油", "柠檬汁"],
                "allergens": [],
                "tags": ["健康", "低卡", "清爽"],
                "is_vegetarian": True,
                "is_vegan": True,
                "is_low_carb": True,
                "is_low_fat": True,
                "health_score": 95,
                "popularity_score": 8.2,
                "image_url": "/static/img/food/default-food.svg",
                "description": "健康轻食，清爽可口",
            },
            {
                "name": "燕麦粥",
                "english_name": "Oatmeal",
                "cuisine": "healthy",
                "meal_type": "breakfast",
                "difficulty": 1,
                "cooking_time": 15,
                "serving_size": 250,
                "calories": 150,
                "protein": 5.8,
                "fat": 3.2,
                "carbohydrates": 28.5,
                "dietary_fiber": 4.8,
                "sugar": 8.5,
                "sodium": 180,
                "potassium": 320,
                "calcium": 120,
                "iron": 2.8,
                "vitamin_c": 2,
                "ingredients": ["燕麦", "牛奶", "蜂蜜", "坚果", "水果"],
                "allergens": ["乳制品", "坚果"],
                "tags": ["健康", "早餐", "高纤维"],
                "is_vegetarian": True,
                "is_high_protein": False,
                "health_score": 90,
                "popularity_score": 8.0,
                "image_url": "/static/img/food/default-food.svg",
                "description": "营养早餐，健康美味",
            },
            # 韩料
            {
                "name": "韩式烤肉",
                "english_name": "Korean BBQ",
                "cuisine": "korean",
                "meal_type": "main",
                "difficulty": 3,
                "cooking_time": 25,
                "serving_size": 180,
                "calories": 400,
                "protein": 32.5,
                "fat": 24.8,
                "carbohydrates": 8.2,
                "dietary_fiber": 1.8,
                "sugar": 6.5,
                "sodium": 850,
                "potassium": 520,
                "calcium": 45,
                "iron": 4.2,
                "vitamin_c": 15,
                "ingredients": ["牛肉", "生菜", "蒜", "辣椒酱", "芝麻油"],
                "allergens": ["芝麻"],
                "tags": ["韩式", "烤肉", "辣味"],
                "is_high_protein": True,
                "health_score": 70,
                "popularity_score": 8.7,
                "image_url": "/static/img/food/default-food.svg",
                "description": "韩式经典，香辣可口",
            },
            # 法餐
            {
                "name": "法式牛排",
                "english_name": "French Steak",
                "cuisine": "french",
                "meal_type": "dinner",  # 改为dinner
                "difficulty": 4,
                "cooking_time": 30,
                "serving_size": 200,
                "calories": 500,
                "protein": 42.5,
                "fat": 32.8,
                "carbohydrates": 2.5,
                "dietary_fiber": 0.5,
                "sugar": 1.2,
                "sodium": 520,
                "potassium": 680,
                "calcium": 25,
                "iron": 5.8,
                "vitamin_c": 2,
                "ingredients": ["牛排", "黄油", "红酒", "香草", "蘑菇"],
                "allergens": ["乳制品"],
                "tags": ["法式", "高级", "牛排"],
                "is_high_protein": True,
                "is_low_carb": True,
                "health_score": random.randint(45, 85),  # 随机健康评分
                "popularity_score": 8.5,
                "image_url": "/static/img/food/default-food.svg",
                "description": "法式经典，精致美味",
            },
            # 添加更多dinner类型
            {
                "name": "红烧肉",
                "english_name": "Braised Pork Belly",
                "cuisine": "chinese",
                "meal_type": "dinner",
                "difficulty": 3,
                "cooking_time": 45,
                "serving_size": 150,
                "calories": 420,
                "protein": 28.5,
                "fat": 30.2,
                "carbohydrates": 8.5,
                "dietary_fiber": 0.8,
                "sugar": 6.2,
                "sodium": 780,
                "potassium": 380,
                "calcium": 35,
                "iron": 3.2,
                "vitamin_c": 2,
                "ingredients": ["五花肉", "生抽", "老抽", "冰糖", "料酒"],
                "allergens": [],
                "tags": ["中式", "经典", "家常菜"],
                "is_high_protein": True,
                "health_score": 60,
                "popularity_score": 9.0,
                "image_url": "/static/img/food/default-food.svg",
                "description": "经典中式菜肴，肥而不腻",
            },
            {
                "name": "烤鸡翅",
                "english_name": "Grilled Chicken Wings",
                "cuisine": "american",
                "meal_type": "dinner",
                "difficulty": 2,
                "cooking_time": 25,
                "serving_size": 120,
                "calories": 320,
                "protein": 25.8,
                "fat": 22.4,
                "carbohydrates": 2.1,
                "dietary_fiber": 0.2,
                "sugar": 1.5,
                "sodium": 620,
                "potassium": 280,
                "calcium": 20,
                "iron": 1.8,
                "vitamin_c": 1,
                "ingredients": ["鸡翅", "蜂蜜", "生抽", "蒜", "胡椒"],
                "allergens": [],
                "tags": ["烤制", "简单", "蛋白质"],
                "is_high_protein": True,
                "health_score": 70,
                "popularity_score": 8.8,
                "image_url": "/static/img/food/default-food.svg",
                "description": "香嫩烤鸡翅，外焦内嫩",
            },
            # 添加snack类型
            {
                "name": "水果沙拉",
                "english_name": "Fruit Salad",
                "cuisine": "healthy",
                "meal_type": "snack",
                "difficulty": 1,
                "cooking_time": 10,
                "serving_size": 150,
                "calories": 85,
                "protein": 1.2,
                "fat": 0.3,
                "carbohydrates": 21.5,
                "dietary_fiber": 3.8,
                "sugar": 18.2,
                "sodium": 5,
                "potassium": 280,
                "calcium": 25,
                "iron": 0.5,
                "vitamin_c": 45,
                "vitamin_a": 120,
                "ingredients": ["苹果", "香蕉", "橙子", "草莓", "柠檬汁"],
                "allergens": [],
                "tags": ["健康", "低卡", "维生素"],
                "is_vegetarian": True,
                "is_vegan": True,
                "is_low_fat": True,
                "health_score": 95,
                "popularity_score": 8.5,
                "image_url": "/static/img/food/default-food.svg",
                "description": "新鲜水果，维生素丰富",
            },
            {
                "name": "坚果",
                "english_name": "Mixed Nuts",
                "cuisine": "healthy",
                "meal_type": "snack",
                "difficulty": 1,
                "cooking_time": 0,
                "serving_size": 30,
                "calories": 180,
                "protein": 6.8,
                "fat": 15.2,
                "carbohydrates": 5.8,
                "dietary_fiber": 3.2,
                "sugar": 1.8,
                "sodium": 2,
                "potassium": 180,
                "calcium": 45,
                "iron": 1.2,
                "vitamin_c": 0,
                "vitamin_e": 8.5,
                "ingredients": ["杏仁", "核桃", "腰果", "开心果"],
                "allergens": ["坚果"],
                "tags": ["健康", "蛋白质", "便携"],
                "is_vegetarian": True,
                "is_vegan": True,
                "is_high_protein": True,
                "health_score": 88,
                "popularity_score": 8.2,
                "image_url": "/static/img/food/default-food.svg",
                "description": "营养坚果，健康零食",
            },
            {
                "name": "酸奶",
                "english_name": "Yogurt",
                "cuisine": "healthy",
                "meal_type": "snack",
                "difficulty": 1,
                "cooking_time": 0,
                "serving_size": 150,
                "calories": 120,
                "protein": 8.5,
                "fat": 3.2,
                "carbohydrates": 12.8,
                "dietary_fiber": 0,
                "sugar": 12.5,
                "sodium": 85,
                "potassium": 280,
                "calcium": 180,
                "iron": 0.2,
                "vitamin_c": 2,
                "ingredients": ["牛奶", "乳酸菌", "蜂蜜"],
                "allergens": ["乳制品"],
                "tags": ["益生菌", "钙质", "蛋白质"],
                "is_vegetarian": True,
                "health_score": 85,
                "popularity_score": 8.7,
                "image_url": "/static/img/food/default-food.svg",
                "description": "富含益生菌，促进消化",
            },
            # 添加更多dessert类型
            {
                "name": "芒果布丁",
                "english_name": "Mango Pudding",
                "cuisine": "healthy",
                "meal_type": "dessert",
                "difficulty": 2,
                "cooking_time": 20,
                "serving_size": 100,
                "calories": 145,
                "protein": 3.2,
                "fat": 2.8,
                "carbohydrates": 28.5,
                "dietary_fiber": 1.2,
                "sugar": 25.8,
                "sodium": 45,
                "potassium": 150,
                "calcium": 65,
                "iron": 0.3,
                "vitamin_c": 25,
                "vitamin_a": 180,
                "ingredients": ["芒果", "牛奶", "明膠", "糖"],
                "allergens": ["乳制品"],
                "tags": ["甜品", "水果", "清爽"],
                "is_vegetarian": True,
                "health_score": 70,
                "popularity_score": 8.3,
                "image_url": "/static/img/food/default-food.svg",
                "description": "香甜芒果布丁，口感丝滑",
            },
            {
                "name": "巧克力蛋糕",
                "english_name": "Chocolate Cake",
                "cuisine": "american",
                "meal_type": "dessert",
                "difficulty": 4,
                "cooking_time": 60,
                "serving_size": 80,
                "calories": 285,
                "protein": 4.2,
                "fat": 12.8,
                "carbohydrates": 42.5,
                "dietary_fiber": 2.1,
                "sugar": 35.8,
                "sodium": 220,
                "potassium": 120,
                "calcium": 85,
                "iron": 1.8,
                "vitamin_c": 0,
                "ingredients": ["面粉", "可可粉", "鸡蛋", "黄油", "糖"],
                "allergens": ["麸质", "鸡蛋", "乳制品"],
                "tags": ["甜品", "巧克力", "庆祝"],
                "is_vegetarian": True,
                "health_score": 45,
                "popularity_score": 9.2,
                "image_url": "/static/img/food/default-food.svg",
                "description": "浓郁巧克力蛋糕，甜蜜诱人",
            },
        ]

        # 批量创建食物数据
        created_count = 0
        for food_data in foods_data:
            food, created = FoodNutrition.objects.get_or_create(name=food_data["name"], defaults=food_data)
            if created:
                created_count += 1
                self.stdout.write(f"✓ 创建食物: {food.name}")
            else:
                self.stdout.write(f"○ 食物已存在: {food.name}")

        self.stdout.write(self.style.SUCCESS(f"数据填充完成！共创建 {created_count} 个食物条目"))

        # 显示统计信息
        total_foods = FoodNutrition.objects.count()
        by_cuisine = {}
        for cuisine, display_name in FoodNutrition.CUISINE_CHOICES:
            count = FoodNutrition.objects.filter(cuisine=cuisine).count()
            if count > 0:
                by_cuisine[display_name] = count

        self.stdout.write("\n📊 数据库统计:")
        self.stdout.write(f"总食物数量: {total_foods}")
        self.stdout.write("按菜系分布:")
        for cuisine, count in by_cuisine.items():
            self.stdout.write(f"  - {cuisine}: {count} 个")
