# Generated by Django 5.2.6 on 2025-09-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShareAnalytics",
        ),
        migrations.DeleteModel(
            name="ShareLink",
        ),
        migrations.DeleteModel(
            name="ShareRecord",
        ),
    ]
