# Generated by Django 4.2.18 on 2025-07-31 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号'),
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '正常'), ('suspended', '已暂停'), ('banned', '已封禁'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='用户状态')),
                ('reason', models.TextField(blank=True, verbose_name='状态变更原因')),
                ('suspended_until', models.DateTimeField(blank=True, null=True, verbose_name='暂停到期时间')),
                ('banned_phone', models.CharField(blank=True, max_length=20, verbose_name='封禁手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户状态',
                'verbose_name_plural': '用户状态',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('free', '免费用户'), ('basic', '基础会员'), ('premium', '高级会员'), ('vip', 'VIP会员')], default='free', max_length=20, verbose_name='会员类型')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='会员开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='会员结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='会员状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户会员',
                'verbose_name_plural': '用户会员',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', '状态变更'), ('phone_ban', '手机号封禁'), ('account_delete', '账号删除'), ('membership_change', '会员变更'), ('role_change', '角色变更')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
