# Generated by Django 4.2.18 on 2025-07-31 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile_phone_userstatus_usermembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
    ]
