# Generated by Django 4.2.18 on 2025-07-31 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_useractionlog_target_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(verbose_name='会话开始时间')),
                ('session_end', models.DateTimeField(blank=True, null=True, verbose_name='会话结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='会话时长(秒)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户会话统计',
                'verbose_name_plural': '用户会话统计',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('api_access', '接口访问'), ('page_view', '页面访问'), ('tool_usage', '工具使用'), ('suggestion_submit', '提交建议'), ('feedback_submit', '提交反馈'), ('profile_update', '资料更新')], max_length=20, verbose_name='活动类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问端点')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户活动日志',
                'verbose_name_plural': '用户活动日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='users_usera_user_id_07b636_idx'), models.Index(fields=['activity_type', 'created_at'], name='users_usera_activit_573fdc_idx'), models.Index(fields=['ip_address', 'created_at'], name='users_usera_ip_addr_4052de_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='API端点')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.FloatField(verbose_name='响应时间(秒)')),
                ('request_size', models.IntegerField(blank=True, null=True, verbose_name='请求大小(字节)')),
                ('response_size', models.IntegerField(blank=True, null=True, verbose_name='响应大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API使用统计',
                'verbose_name_plural': 'API使用统计',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='users_apius_endpoin_caacf2_idx'), models.Index(fields=['user', 'created_at'], name='users_apius_user_id_dae3dc_idx'), models.Index(fields=['status_code', 'created_at'], name='users_apius_status__6e3b2f_idx')],
            },
        ),
    ]
