# Generated by Django 4.2.7 on 2025-08-01 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_usersessionstats_useractivitylog_apiusagestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('life', '生活模式'), ('work', '极客模式'), ('training', '狂暴模式'), ('emo', 'Emo模式')], default='work', max_length=20, verbose_name='主题模式')),
                ('theme_style', models.CharField(choices=[('default', '默认样式'), ('dark', '深色样式'), ('light', '浅色样式'), ('custom', '自定义样式')], default='default', max_length=20, verbose_name='主题样式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户主题',
                'verbose_name_plural': '用户主题',
            },
        ),
    ]
