# Generated by Django 4.2.7 on 2025-08-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usertheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertheme',
            name='last_switch_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后切换时间'),
        ),
        migrations.AddField(
            model_name='usertheme',
            name='switch_count',
            field=models.IntegerField(default=0, verbose_name='切换次数'),
        ),
    ]
