# Generated by Django 4.2.7 on 2025-08-02 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='action',
            field=models.CharField(choices=[('status_change', '状态变更'), ('phone_ban', '手机号封禁'), ('account_delete', '账号删除'), ('membership_change', '会员变更'), ('role_change', '角色变更'), ('avatar_upload', '头像上传')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_actions', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
    ]
