# Generated by Django 4.2.23 on 2025-08-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_useractionlog_user_alter_useractionlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('work', '极客模式'), ('life', '生活模式'), ('training', '狂暴模式'), ('emo', 'Emo模式')], max_length=20, verbose_name='模式')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('last_click_time', models.DateTimeField(auto_now=True, verbose_name='最后点击时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户模式偏好',
                'verbose_name_plural': '用户模式偏好',
                'ordering': ['-click_count', '-last_click_time'],
                'indexes': [models.Index(fields=['user', 'mode'], name='users_userm_user_id_6aa6c0_idx'), models.Index(fields=['user', 'click_count'], name='users_userm_user_id_e0bf14_idx')],
                'unique_together': {('user', 'mode')},
            },
        ),
    ]
