# Generated by Django 5.2.6 on 2025-09-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_usermodepreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractionlog",
            name="admin_user",
        ),
        migrations.RemoveField(
            model_name="useractionlog",
            name="target_user",
        ),
        migrations.RemoveField(
            model_name="useractionlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usermembership",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="usermodepreference",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usermodepreference",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usersessionstats",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usertheme",
            name="user",
        ),
        migrations.DeleteModel(
            name="APIUsageStats",
        ),
        migrations.DeleteModel(
            name="UserActionLog",
        ),
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
        migrations.DeleteModel(
            name="UserMembership",
        ),
        migrations.DeleteModel(
            name="UserModePreference",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="UserSessionStats",
        ),
        migrations.DeleteModel(
            name="UserStatus",
        ),
        migrations.DeleteModel(
            name="UserTheme",
        ),
    ]
