# Generated by Django 5.0.1 on 2025-09-09 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_usertheme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="users_profile",
        ),
        migrations.AlterModelTable(
            name="usertheme",
            table="users_usertheme",
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("status_change", "状态变更"),
                            ("phone_ban", "手机号封禁"),
                            ("account_delete", "账号删除"),
                            ("membership_change", "会员变更"),
                            ("role_change", "角色变更"),
                            ("avatar_upload", "头像上传"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("details", models.TextField(verbose_name="操作详情")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="操作时间")),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="管理员",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标用户",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户操作日志",
                "verbose_name_plural": "用户操作日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "membership_type",
                    models.CharField(
                        choices=[("free", "免费用户"), ("basic", "基础会员"), ("premium", "高级会员"), ("vip", "VIP会员")],
                        default="free",
                        max_length=20,
                        verbose_name="会员类型",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True, verbose_name="会员开始时间")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="会员结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="会员状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="membership", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "用户会员",
                "verbose_name_plural": "用户会员",
                "db_table": "apps_users_usermembership",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "普通用户"), ("admin", "管理员")], default="user", max_length=10, verbose_name="用户角色"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="role", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色",
                "verbose_name_plural": "用户角色",
                "db_table": "apps.users_userrole",
            },
        ),
        migrations.CreateModel(
            name="UserSessionStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_start", models.DateTimeField(verbose_name="会话开始时间")),
                ("session_end", models.DateTimeField(blank=True, null=True, verbose_name="会话结束时间")),
                ("duration", models.IntegerField(blank=True, null=True, verbose_name="会话时长(秒)")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(verbose_name="用户代理")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="session_stats", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "用户会话统计",
                "verbose_name_plural": "用户会话统计",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "正常"), ("suspended", "已暂停"), ("banned", "已封禁"), ("deleted", "已删除")],
                        default="active",
                        max_length=20,
                        verbose_name="用户状态",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="状态变更原因")),
                ("suspended_until", models.DateTimeField(blank=True, null=True, verbose_name="暂停到期时间")),
                ("banned_phone", models.CharField(blank=True, max_length=20, verbose_name="封禁手机号")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="status", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "用户状态",
                "verbose_name_plural": "用户状态",
            },
        ),
        migrations.CreateModel(
            name="APIUsageStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=255, verbose_name="API端点")),
                ("method", models.CharField(max_length=10, verbose_name="请求方法")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("status_code", models.IntegerField(verbose_name="状态码")),
                ("response_time", models.FloatField(verbose_name="响应时间(秒)")),
                ("request_size", models.IntegerField(blank=True, null=True, verbose_name="请求大小(字节)")),
                ("response_size", models.IntegerField(blank=True, null=True, verbose_name="响应大小(字节)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="访问时间")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API使用统计",
                "verbose_name_plural": "API使用统计",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["endpoint", "created_at"], name="users_apius_endpoin_caacf2_idx"),
                    models.Index(fields=["user", "created_at"], name="users_apius_user_id_dae3dc_idx"),
                    models.Index(fields=["status_code", "created_at"], name="users_apius_status__6e3b2f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("api_access", "接口访问"),
                            ("page_view", "页面访问"),
                            ("tool_usage", "工具使用"),
                            ("suggestion_submit", "提交建议"),
                            ("feedback_submit", "提交反馈"),
                            ("profile_update", "资料更新"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, null=True, verbose_name="用户代理")),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True, verbose_name="访问端点")),
                ("method", models.CharField(blank=True, max_length=10, null=True, verbose_name="请求方法")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="状态码")),
                ("response_time", models.FloatField(blank=True, null=True, verbose_name="响应时间(秒)")),
                ("details", models.JSONField(blank=True, null=True, verbose_name="详细信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户活动日志",
                "verbose_name_plural": "用户活动日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "activity_type", "created_at"], name="users_usera_user_id_07b636_idx"),
                    models.Index(fields=["activity_type", "created_at"], name="users_usera_activit_573fdc_idx"),
                    models.Index(fields=["ip_address", "created_at"], name="users_usera_ip_addr_4052de_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserModePreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("work", "极客模式"), ("life", "生活模式"), ("training", "狂暴模式"), ("emo", "Emo模式")],
                        max_length=20,
                        verbose_name="模式",
                    ),
                ),
                ("click_count", models.IntegerField(default=0, verbose_name="点击次数")),
                ("last_click_time", models.DateTimeField(auto_now=True, verbose_name="最后点击时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mode_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户模式偏好",
                "verbose_name_plural": "用户模式偏好",
                "ordering": ["-click_count", "-last_click_time"],
                "indexes": [
                    models.Index(fields=["user", "mode"], name="users_userm_user_id_6aa6c0_idx"),
                    models.Index(fields=["user", "click_count"], name="users_userm_user_id_e0bf14_idx"),
                ],
                "unique_together": {("user", "mode")},
            },
        ),
    ]
