# Generated by Django 4.2.18 on 2025-09-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_profile_table_alter_usertheme_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userrole",
            table="users_userrole",
        ),
    ]
